<?php
/**
 * API Dashboard Endpoint
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Check request method
if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    sendApiResponse(false, 'Invalid request method', null, 405);
}

// Get user from request headers (Token-based auth simulation)
// In a real app, we would verify a JWT token here.
// For now, we expect 'User-ID' header for simplicity safely within this closed system context, 
// OR simpler: pass user_id as query param for this MVP if headers are tricky in testing.
// Let's rely on query param `user_id` for MVP speed, but ideally headers.
// Actually, `config.php` doesn't implement auth check yet. 
// I will just require `user_id` parameter.

$userId = $_GET['user_id'] ?? null;
$branchId = $_GET['branch_id'] ?? null;

if (!$userId) {
    sendApiResponse(false, 'User ID is required', null, 400);
}

try {
// Manually set session for existing functions to work if they rely on $_SESSION['user_id']
// But functions usually take arguments or we can mock it.
// `getDashboardStats` takes arguments. `student/dashboard.php` logic needs to be adapted.

// Fetch user role
$sql = "SELECT u.*, r.role_name, b.branch_name 
        FROM users u 
        LEFT JOIN roles r ON u.role_id = r.id 
        LEFT JOIN branches b ON u.branch_id = b.id 
        WHERE u.id = ?";
$stmt = executeQuery($sql, 'i', [$userId]);
$user = fetchOne($stmt);

// Determine if user is Super Admin
$isSuperAdmin = ($user['role_name'] ?? '') === 'Super Admin';

// For Super Admin, use provided branch_id (null = all branches)
// For other roles, use their assigned branch_id
if ($isSuperAdmin) {
    // Super Admin can filter by branch or view all (null = all branches)
    // Only set branchId if it's not null, not empty, and not 'null' string
    if ($branchId !== null && $branchId !== '' && $branchId !== 'null') {
        $branchId = (int)$branchId;
    } else {
        $branchId = null; // null means "All Branches"
    }
} else {
    // Other roles are restricted to their assigned branch
    $branchId = $user['branch_id'] ?? null;
}

if (!$user) {
    sendApiResponse(false, 'User not found', null, 404);
}

$roleName = $user['role_name'];
$responseData = [];

// Load necessary includes
if (file_exists(ABSPATH . 'includes/dashboard-functions.php')) {
    require_once ABSPATH . 'includes/dashboard-functions.php';
}
if ($roleName === 'Student') {
    // STUDENT DASHBOARD LOGIC
    $student = getStudentByUserId($userId);
    
    if (!$student) {
        sendApiResponse(false, 'Student record not found', null, 404);
    }
    
    $studentId = $student['id'];
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? null;
    
    // 1. Attendance Stats
    $sql = "SELECT 
            COUNT(*) as total_days,
            COALESCE(SUM(CASE WHEN sa.status = 'Present' THEN 1 ELSE 0 END), 0) as present_days,
            COALESCE(SUM(CASE WHEN sa.status = 'Absent' THEN 1 ELSE 0 END), 0) as absent_days
            FROM student_attendance sa
            WHERE sa.student_id = ?";
    $stmt = executeQuery($sql, 'i', [$studentId]);
    $attendanceData = fetchOne($stmt);
    
    $attendancePercentage = 0;
    if (($attendanceData['total_days'] ?? 0) > 0) {
        $attendancePercentage = round(($attendanceData['present_days'] / $attendanceData['total_days']) * 100, 1);
    }
    
    $responseData['attendance'] = [
        'percentage' => $attendancePercentage,
        'present' => $attendanceData['present_days'],
        'absent' => $attendanceData['absent_days'],
        'total' => $attendanceData['total_days']
    ];
    
    // 2. Today's Status
    $sql = "SELECT sa.status 
            FROM student_attendance sa
            WHERE sa.student_id = ? AND sa.attendance_date = CURDATE()";
    $stmt = executeQuery($sql, 'i', [$studentId]);
    $todayAttendance = fetchOne($stmt);
    $responseData['today_status'] = $todayAttendance['status'] ?? 'Not Marked';
    
    // 3. Upcoming Assignments
    $sql = "SELECT COUNT(*) as count 
            FROM assignments a
            WHERE a.class_id = ? AND a.due_date >= CURDATE() AND a.session_id = ?";
    $stmt = executeQuery($sql, 'ii', [$student['current_class_id'], $sessionId]);
    $responseData['upcoming_assignments'] = fetchOne($stmt)['count'] ?? 0;
    
    // 4. Upcoming Exams
    $sql = "SELECT COUNT(*) as count 
            FROM exam_schedule es
            INNER JOIN exams e ON es.exam_id = e.id
            WHERE e.class_id = ? AND es.exam_date >= CURDATE()";
    $stmt = executeQuery($sql, 'i', [$student['current_class_id']]);
    $responseData['upcoming_exams'] = fetchOne($stmt)['count'] ?? 0;
    
    // 5. Outstanding Fees (Summary)
    $sqlInv = "SELECT COALESCE(SUM(due_amount), 0) as total FROM fee_invoices WHERE student_id = ? AND due_amount > 0";
    $stmtInv = executeQuery($sqlInv, 'i', [$studentId]);
    $invTotal = fetchOne($stmtInv)['total'] ?? 0;
    
    $sqlFee = "SELECT COALESCE(SUM(due_amount), 0) as total FROM monthly_fee_assignments WHERE student_id = ? AND due_amount > 0";
    $stmtFee = executeQuery($sqlFee, 'i', [$studentId]);
    $feeTotal = fetchOne($stmtFee)['total'] ?? 0;
    
    $responseData['outstanding_fees'] = $invTotal + $feeTotal;
    
    // 6. Recent Announcements
    $sql = "SELECT title, content, created_at FROM announcements 
            WHERE (target_audience = 'All' OR target_audience = 'Students')
            AND (start_date IS NULL OR start_date <= CURDATE())
            AND (end_date IS NULL OR end_date >= CURDATE())
            ORDER BY created_at DESC LIMIT 3";
    $responseData['announcements'] = fetchAll(executeQuery($sql));
    
    // 7. Today's Timetable
    $dayOfWeek = strtoupper(date('l')); // e.g., MONDAY
    // Fix: DAYNAME returns mixed case usually, but let's check DB usage. 
    // The query in dashboard.php uses UPPER(DAYNAME(CURDATE()))
    
    $sql = "SELECT t.start_time, t.end_time, s.subject_name, s.subject_code, t.room_no
            FROM timetable t
            INNER JOIN subjects s ON t.subject_id = s.id
            WHERE t.class_id = ? AND t.session_id = ? 
            AND t.day_of_week = UPPER(DAYNAME(CURDATE()))
            ORDER BY t.start_time";
    $stmt = executeQuery($sql, 'ii', [$student['current_class_id'], $sessionId]);
    $responseData['timetable'] = fetchAll($stmt);

} elseif ($roleName === 'Teacher') {
    // TEACHER DASHBOARD LOGIC (Simplified)
    // For now, give basics
    $responseData['message'] = 'Teacher dashboard data';
    // TODO: Implement teacher specific stats
} else {
    // ADMIN/STAFF DASHBOARD LOGIC
    // Use the existing function
    // Use the branch_id determined earlier (already set for Super Admin or user's branch)
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? null;
    
    $stats = getDashboardStats($branchId, $sessionId, false); // false to skip cache for real-time testing
    $responseData['stats'] = $stats;
    
    // Add activities and top_classes if they exist in stats
    if (isset($stats['activities'])) {
        $responseData['activities'] = $stats['activities'];
    }
    if (isset($stats['top_classes'])) {
        $responseData['top_classes'] = $stats['top_classes'];
    }
}

sendApiResponse(true, 'Dashboard data retrieved', $responseData);

} catch (Exception $e) {
    sendApiResponse(false, 'Failed to load dashboard data: ' . $e->getMessage(), null, 500);
} catch (Error $e) {
    sendApiResponse(false, 'Server error: ' . $e->getMessage(), null, 500);
}
