<?php
/**
 * AJAX: Create Calendar Event
 * 
 * Create a new academic calendar event
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonResponse(false, 'Invalid request method');
}

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied. Only Admin and Super Admin can create calendar events.');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin']);
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$eventTitle = sanitize($data['title'] ?? '');
$eventType = sanitize($data['event_type'] ?? 'Event');
$description = sanitize($data['description'] ?? '');
$startDate = $data['start_date'] ?? '';
$endDate = $data['end_date'] ?? '';
$branchId = $currentUser['branch_id'] ?? null;

$errors = [];
if (empty($eventTitle)) $errors[] = 'Event title is required';
if (empty($eventType)) $errors[] = 'Event type is required';
if (empty($startDate)) $errors[] = 'Start date is required';
if (empty($endDate)) $errors[] = 'End date is required';

// Validate event type
$allowedTypes = ['Holiday', 'Exam', 'Event', 'Meeting', 'Other'];
if (!in_array($eventType, $allowedTypes)) {
    $errors[] = 'Invalid event type';
}

// Validate dates
if (!empty($startDate) && !empty($endDate)) {
    $start = strtotime($startDate);
    $end = strtotime($endDate);
    if ($end < $start) {
        $errors[] = 'End date cannot be before start date';
    }
}

if (!empty($errors)) {
    jsonResponse(false, implode(', ', $errors));
}

try {
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? 1;
    
    $sql = "INSERT INTO academic_calendar (
        session_id, event_title, event_type, start_date, end_date, 
        description, branch_id, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, NOW())";
    
    $stmt = executeQuery($sql, 'isssssi', [
        $sessionId, $eventTitle, $eventType, $startDate, $endDate, 
        $description, $branchId
    ]);
    
    $eventId = getLastInsertId();
    
    logActivity(
        $currentUser['id'],
        'Create Calendar Event',
        'Academic Calendar',
        "Created calendar event: $eventTitle"
    );
    
    jsonResponse(true, 'Calendar event created successfully!', ['id' => $eventId]);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to create calendar event: ' . $e->getMessage());
}

