<?php
/**
 * AJAX: Create/Update Syllabus
 * 
 * Create or update syllabus for a class-subject combination
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonResponse(false, 'Invalid request method');
}

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin', 'Teacher']);
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$classId = $data['class_id'] ?? null;
$subjectId = $data['subject_id'] ?? null;
$title = sanitize($data['title'] ?? '');
$syllabusContent = sanitize($data['description'] ?? $data['syllabus'] ?? '');

$errors = [];
if (empty($classId)) $errors[] = 'Class is required';
if (empty($subjectId)) $errors[] = 'Subject is required';
if (empty($title)) $errors[] = 'Title is required';
if (empty($syllabusContent)) $errors[] = 'Syllabus content is required';

if (!empty($errors)) {
    jsonResponse(false, implode(', ', $errors));
}

try {
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? 1;
    
    // Handle file upload if provided
    $filePath = null;
    if (isset($_FILES['file']) && $_FILES['file']['error'] == 0) {
        $uploadDir = ABSPATH . 'uploads/syllabus/';
        if (!file_exists($uploadDir)) {
            mkdir($uploadDir, 0755, true);
        }
        
        $uploadResult = uploadFile($_FILES['file'], $uploadDir, ['pdf', 'doc', 'docx']);
        if ($uploadResult['success']) {
            $filePath = 'uploads/syllabus/' . $uploadResult['filename'];
        }
    }
    
    // Check if syllabus already exists
    $checkSql = "SELECT id FROM curriculum WHERE class_id = ? AND subject_id = ? AND session_id = ?";
    $stmt = executeQuery($checkSql, 'iii', [$classId, $subjectId, $sessionId]);
    $existing = fetchOne($stmt);
    
    if ($existing) {
        // Update existing
        $sql = "UPDATE curriculum SET syllabus = ?, learning_objectives = ?";
        $params = [$syllabusContent, $title];
        $types = 'ss';
        
        if ($filePath) {
            $sql .= ", file_path = ?";
            $params[] = $filePath;
            $types .= 's';
        }
        
        $sql .= " WHERE id = ?";
        $params[] = $existing['id'];
        $types .= 'i';
        
        $stmt = executeQuery($sql, $types, $params);
        $message = 'Syllabus updated successfully!';
        $syllabusId = $existing['id'];
    } else {
        // Insert new
        $sql = "INSERT INTO curriculum (class_id, subject_id, session_id, syllabus, learning_objectives, file_path)
                VALUES (?, ?, ?, ?, ?, ?)";
        $stmt = executeQuery($sql, 'iiisss', [
            $classId, $subjectId, $sessionId, $syllabusContent, $title, $filePath
        ]);
        $syllabusId = getLastInsertId();
        $message = 'Syllabus created successfully!';
    }
    
    logActivity(
        $currentUser['id'],
        'Create/Update Syllabus',
        'Syllabus',
        "Created/updated syllabus for class ID: $classId, subject ID: $subjectId"
    );
    
    jsonResponse(true, $message, ['id' => $syllabusId]);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to create syllabus: ' . $e->getMessage());
}

