<?php
/**
 * AJAX: Create Assignment
 * 
 * Create a new assignment
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonResponse(false, 'Invalid request method');
}

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin', 'Teacher']);
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$classId = $data['class_id'] ?? null;
$subjectId = $data['subject_id'] ?? null;
$title = sanitize($data['title'] ?? '');
$description = sanitize($data['description'] ?? '');
$dueDate = $data['due_date'] ?? '';

$errors = [];
if (empty($classId)) $errors[] = 'Class is required';
if (empty($subjectId)) $errors[] = 'Subject is required';
if (empty($title)) $errors[] = 'Title is required';
if (empty($dueDate)) $errors[] = 'Due date is required';

if (!empty($errors)) {
    jsonResponse(false, implode(', ', $errors));
}

try {
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? 1;
    
    // Get teacher ID if user is a teacher
    $teacherId = null;
    if ($currentUser['role_name'] === 'Teacher') {
        $teacherSql = "SELECT id FROM staff WHERE user_id = ?";
        $teacherStmt = executeQuery($teacherSql, 'i', [$currentUser['id']]);
        $teacher = fetchOne($teacherStmt);
        $teacherId = $teacher['id'] ?? null;
    }
    
    $sql = "INSERT INTO assignments (
        class_id, subject_id, session_id, title, description, due_date, 
        created_by, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, NOW())";
    
    $stmt = executeQuery($sql, 'iiisssi', [
        $classId, $subjectId, $sessionId, $title, $description, $dueDate, $currentUser['id']
    ]);
    
    $assignmentId = getLastInsertId();
    
    logActivity(
        $currentUser['id'],
        'Create Assignment',
        'Assignments',
        "Created assignment: $title for class ID: $classId"
    );
    
    jsonResponse(true, 'Assignment created successfully!', ['id' => $assignmentId]);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to create assignment: ' . $e->getMessage());
}

