<?php
/**
 * AJAX: Create Lesson Plan
 * 
 * Create a new lesson plan
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonResponse(false, 'Invalid request method');
}

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin', 'Teacher']);
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$classId = $data['class_id'] ?? null;
$subjectId = $data['subject_id'] ?? null;
$topic = sanitize($data['topic'] ?? '');
$objectives = sanitize($data['objectives'] ?? '');
$content = sanitize($data['content'] ?? '');
$teachingMethods = sanitize($data['teaching_methods'] ?? '');
$assessment = sanitize($data['assessment'] ?? '');
$planDate = $data['date'] ?? $data['plan_date'] ?? '';

$errors = [];
if (empty($classId)) $errors[] = 'Class is required';
if (empty($subjectId)) $errors[] = 'Subject is required';
if (empty($topic)) $errors[] = 'Topic is required';
if (empty($objectives)) $errors[] = 'Objectives are required';
if (empty($content)) $errors[] = 'Content is required';
if (empty($planDate)) $errors[] = 'Plan date is required';

if (!empty($errors)) {
    jsonResponse(false, implode(', ', $errors));
}

try {
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? 1;
    
    // Get teacher ID
    $teacherId = null;
    if ($currentUser['role_name'] === 'Teacher') {
        $teacherSql = "SELECT id FROM staff WHERE user_id = ?";
        $teacherStmt = executeQuery($teacherSql, 'i', [$currentUser['id']]);
        $teacher = fetchOne($teacherStmt);
        $teacherId = $teacher['id'] ?? null;
    } else {
        // For admin, try to get teacher from class_subjects
        $teacherSql = "SELECT teacher_id FROM class_subjects 
                       WHERE class_id = ? AND subject_id = ? AND session_id = ? 
                       LIMIT 1";
        $teacherStmt = executeQuery($teacherSql, 'iii', [$classId, $subjectId, $sessionId]);
        $teacher = fetchOne($teacherStmt);
        $teacherId = $teacher['teacher_id'] ?? null;
    }
    
    if (!$teacherId) {
        jsonResponse(false, 'Teacher not assigned to this class-subject combination');
    }
    
    $sql = "INSERT INTO lesson_plans (
        teacher_id, class_id, subject_id, session_id, lesson_title, lesson_date,
        objectives, content, methodology, assessment, status, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'Published', NOW())";
    
    $stmt = executeQuery($sql, 'iiiissssss', [
        $teacherId, $classId, $subjectId, $sessionId, $topic, $planDate,
        $objectives, $content, $teachingMethods, $assessment
    ]);
    
    $lessonPlanId = getLastInsertId();
    
    logActivity(
        $currentUser['id'],
        'Create Lesson Plan',
        'Lesson Plans',
        "Created lesson plan: $topic for class ID: $classId"
    );
    
    jsonResponse(true, 'Lesson plan created successfully!', ['id' => $lessonPlanId]);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to create lesson plan: ' . $e->getMessage());
}

