<?php
/**
 * AJAX: Get All Subjects
 * 
 * Fetch all active subjects
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded (config might set it to 1)
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication - verify user exists and is active
    $sql = "SELECT id FROM users WHERE id = ? AND is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $user = fetchOne($stmt);
    
    if (!$user) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
}

try {
    // Get all active subjects
    // Note: subjects table doesn't have branch_id, so we don't join with branches
    $sql = "SELECT s.id, s.subject_name, s.subject_code, s.subject_type, s.description, s.is_active, s.created_at
            FROM subjects s 
            WHERE s.is_active = 1
            ORDER BY s.subject_name";

    $stmt = executeQuery($sql);
    $subjects = fetchAll($stmt);

    // Add class_count for each subject (number of classes this subject is assigned to)
    if (!empty($subjects)) {
        foreach ($subjects as &$subject) {
            $countSql = "SELECT COUNT(DISTINCT cs.class_id) as class_count
                         FROM class_subjects cs
                         WHERE cs.subject_id = ?";
            $countStmt = executeQuery($countSql, 'i', [$subject['id']]);
            $countResult = fetchOne($countStmt);
            $subject['class_count'] = $countResult['class_count'] ?? 0;
        }
        unset($subject);
    }

    jsonResponse(true, 'Subjects loaded', $subjects);
} catch (Exception $e) {
    // Ensure clean JSON error response
    ob_clean();
    jsonResponse(false, 'Failed to load subjects: ' . $e->getMessage());
}

