<?php
/**
 * AJAX: Add Expense
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$branchId = !empty($data['branch_id']) ? (int)$data['branch_id'] : null;
$category = sanitize($data['expense_category'] ?? '');
$amount = (float)($data['amount'] ?? 0);
$expenseDate = $data['expense_date'] ?? date('Y-m-d');
$paymentMethod = sanitize($data['payment_method'] ?? '');
$referenceNo = sanitize($data['reference_no'] ?? '');
$description = sanitize($data['description'] ?? '');

if (empty($category) || $amount <= 0) {
    jsonResponse(false, 'Category and amount are required');
}

// If not super admin, use user's branch
if (!hasRole(['Super Admin']) && empty($branchId)) {
    $branchId = $currentUser['branch_id'] ?? null;
}

$sql = "INSERT INTO expenses (branch_id, expense_category, amount, expense_date, payment_method, reference_no, description, recorded_by)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = executeQuery($sql, 'isdssssi', [
    $branchId, $category, $amount, $expenseDate, $paymentMethod, $referenceNo, $description, $currentUser['id']
]);

if ($stmt) {
    logActivity($currentUser['id'], 'Add Expense', 'Fees', "Added expense: $category - " . formatCurrency($amount));
    jsonResponse(true, 'Expense record added successfully!');
} else {
    jsonResponse(false, 'Failed to add expense record');
}

