<?php
/**
 * AJAX: Add Fee Structure
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$classId = (int)($data['class_id'] ?? 0);
$feeTypeId = (int)($data['fee_type_id'] ?? 0);
$sessionId = (int)($data['session_id'] ?? 0);
$amount = (float)($data['amount'] ?? 0);
$frequency = $data['frequency'] ?? 'Monthly';
$dueDate = $data['due_date'] ?? null;
$isMandatory = isset($data['is_mandatory']) ? (int)$data['is_mandatory'] : 0;

if (empty($classId) || empty($feeTypeId) || empty($sessionId) || $amount <= 0) {
    jsonResponse(false, 'All required fields must be filled');
}

// Check if structure already exists
$checkSql = "SELECT id FROM fee_structures WHERE class_id = ? AND fee_type_id = ? AND session_id = ?";
$stmt = executeQuery($checkSql, 'iii', [$classId, $feeTypeId, $sessionId]);
if (fetchOne($stmt)) {
    jsonResponse(false, 'Fee structure already exists for this class and fee type');
}

$sql = "INSERT INTO fee_structures (class_id, fee_type_id, session_id, amount, frequency, due_date, is_mandatory)
        VALUES (?, ?, ?, ?, ?, ?, ?)";

$stmt = executeQuery($sql, 'iiidssi', [
    $classId, $feeTypeId, $sessionId, $amount, $frequency, $dueDate, $isMandatory
]);

if ($stmt) {
    logActivity($currentUser['id'], 'Add Fee Structure', 'Fees', "Added fee structure for class ID: $classId");
    jsonResponse(true, 'Fee structure added successfully!');
} else {
    jsonResponse(false, 'Failed to add fee structure');
}

