<?php
/**
 * AJAX: Assign Monthly Fees to Students
 * 
 * Automatically assigns monthly tuition fees to all enrolled students
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$month = $data['month'] ?? '';
$feeTypeId = (int)($data['fee_type_id'] ?? 0);
$classId = $data['class_id'] ?? '';
$sessionId = (int)($data['session_id'] ?? 0);
$dueDate = $data['due_date'] ?? null;

if (empty($month) || empty($feeTypeId) || empty($sessionId)) {
    jsonResponse(false, 'All required fields must be filled');
}

// Validate month format
if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
    jsonResponse(false, 'Invalid month format. Use YYYY-MM');
}

// Check if required tables exist
global $conn;
$tableCheck = $conn->query("SHOW TABLES LIKE 'monthly_fee_assignments'");
if ($tableCheck->num_rows == 0) {
    jsonResponse(false, 'Database tables not found. Please run the database schema: database/monthly_tuition_fees_schema.sql');
}

beginTransaction();

try {
    // Get enrolled students with their discount information
    $studentsSql = "SELECT s.*, s.discount_type, s.discount_value, c.id as class_id, fs.amount, fs.due_date as structure_due_date
                    FROM students s
                    INNER JOIN classes c ON s.current_class_id = c.id
                    INNER JOIN fee_structures fs ON fs.class_id = c.id AND fs.fee_type_id = ? AND fs.session_id = ? AND fs.frequency = 'Monthly'
                    WHERE s.status = 'Active' AND s.current_class_id IS NOT NULL";
    
    $params = [$feeTypeId, $sessionId];
    $types = 'ii';
    
    if (!empty($classId)) {
        $studentsSql .= " AND s.current_class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    $studentsStmt = executeQuery($studentsSql, $types, $params);
    if ($studentsStmt === false) {
        throw new Exception('Failed to fetch students: ' . $conn->error);
    }
    
    $students = fetchAll($studentsStmt);
    
    if (empty($students)) {
        jsonResponse(false, 'No enrolled students found matching the criteria. Make sure students are enrolled and fee structures are defined for their classes.');
    }
    
    // Check for graduated classes before processing
    $graduatedClasses = [];
    foreach ($students as $student) {
        if (!empty($student['class_id'])) {
            if (isClassGraduated($student['class_id'])) {
                $classInfo = getClassGraduationStatus($student['class_id']);
                if ($classInfo && !in_array($classInfo['class_name'], $graduatedClasses)) {
                    $graduatedClasses[] = $classInfo['class_name'];
                }
            }
        }
    }
    
    if (!empty($graduatedClasses)) {
        rollbackTransaction();
        jsonResponse(false, 'Cannot assign fees to students in graduated classes: ' . implode(', ', $graduatedClasses) . '. Financial operations are disabled for graduated classes.');
    }
    
    $assignedCount = 0;
    $skippedCount = 0;
    $totalAmount = 0;
    
    foreach ($students as $student) {
        // Check if already assigned for this month
        $checkSql = "SELECT id FROM monthly_fee_assignments 
                     WHERE student_id = ? AND fee_type_id = ? AND month = ? AND session_id = ?";
        $checkStmt = executeQuery($checkSql, 'iisi', [$student['id'], $feeTypeId, $month, $sessionId]);
        
        if (fetchOne($checkStmt)) {
            $skippedCount++;
            continue;
        }
        
        // Use due date from form or structure, or calculate default (5th of next month)
        $assignmentDueDate = $dueDate;
        if (!$assignmentDueDate && $student['structure_due_date']) {
            $assignmentDueDate = $student['structure_due_date'];
        }
        if (!$assignmentDueDate) {
            // Default: 5th of the month
            $assignmentDueDate = date('Y-m-05', strtotime($month . '-01'));
        }
        
        // Calculate discount
        $originalAmount = (float)$student['amount'];
        $discountAmount = 0.00;
        $discountType = $student['discount_type'] ?? null;
        $discountValue = $student['discount_value'] ?? null;
        
        if ($discountType && $discountValue) {
            if ($discountType === 'Fixed') {
                // Fixed amount discount
                $discountAmount = min((float)$discountValue, $originalAmount); // Don't exceed original amount
            } elseif ($discountType === 'Percentage') {
                // Percentage discount
                $discountAmount = ($originalAmount * (float)$discountValue) / 100;
            }
        }
        
        // Calculate final amount after discount
        $finalAmount = $originalAmount - $discountAmount;
        $finalAmount = max(0.00, $finalAmount); // Ensure non-negative
        
        // Create monthly assignment
        $insertSql = "INSERT INTO monthly_fee_assignments 
                      (student_id, class_id, fee_type_id, session_id, month, amount, original_amount, 
                       discount_amount, discount_type, due_date, 
                       assigned_amount, paid_amount, due_amount, status, assigned_by)
                      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, 'Assigned', ?)";
        
        // Type string: i(student_id) + i(class_id) + i(fee_type_id) + i(session_id) + s(month) + 
        //             d(amount) + d(original_amount) + d(discount_amount) + s(discount_type) + 
        //             s(due_date) + d(assigned_amount) + d(due_amount) + i(assigned_by) = 13 params
        $assignmentStmt = executeQuery($insertSql, 'iiiisdddsdsdi', [
            $student['id'], $student['class_id'], $feeTypeId, $sessionId, $month, 
            $finalAmount, $originalAmount, $discountAmount, $discountType,
            $assignmentDueDate, $finalAmount, $finalAmount, getCurrentUser()['id']
        ]);
        
        if ($assignmentStmt === false) {
            throw new Exception('Failed to create monthly assignment: ' . $conn->error);
        }
        
        $assignmentId = getLastInsertId();
        
        // Get current balance first
        $balanceSql = "SELECT balance FROM student_fee_ledger 
                       WHERE student_id = ? AND session_id = ? 
                       ORDER BY id DESC LIMIT 1";
        $balanceStmt = executeQuery($balanceSql, 'ii', [$student['id'], $sessionId]);
        if ($balanceStmt === false) {
            throw new Exception('Failed to get balance: ' . $conn->error);
        }
        
        $balanceRow = fetchOne($balanceStmt);
        $currentBalance = $balanceRow ? (float)$balanceRow['balance'] : 0.00;
        $newBalance = $currentBalance + $finalAmount;
        
        // Update student fee ledger - record the final amount (after discount)
        // The discount is applied internally and not shown to students
        $ledgerSql = "INSERT INTO student_fee_ledger 
                      (student_id, session_id, transaction_type, reference_id, reference_type, 
                       month, debit_amount, credit_amount, balance, description)
                      VALUES (?, ?, 'Assignment', ?, 'monthly_assignment', ?, ?, 0, ?, ?)";
        
        $description = "Monthly fee assignment for " . date('F Y', strtotime($month . '-01'));
        if ($discountAmount > 0) {
            // Include discount info in description for audit purposes (not shown to students)
            $description .= " (Original: " . formatCurrency($originalAmount);
            if ($discountType === 'Fixed') {
                $description .= ", Discount: " . formatCurrency($discountAmount) . ")";
            } else {
                $description .= ", Discount: " . number_format($discountValue, 2) . "% = " . formatCurrency($discountAmount) . ")";
            }
        }
        
        // Types: i=student_id, i=session_id, i=reference_id, s=month, d=debit_amount, d=balance, s=description
        // 7 parameters: student_id, session_id, reference_id, month, debit_amount, balance, description
        $ledgerStmt = executeQuery($ledgerSql, 'iiisdds', [
            $student['id'], $sessionId, $assignmentId, $month, $finalAmount, $newBalance, $description
        ]);
        
        if ($ledgerStmt === false) {
            throw new Exception('Failed to update ledger: ' . $conn->error);
        }
        
        // Update student fee balance
        $balanceUpdateSql = "INSERT INTO student_fee_balance 
                       (student_id, session_id, total_assigned, total_due, last_updated)
                       VALUES (?, ?, ?, ?, NOW())
                       ON DUPLICATE KEY UPDATE 
                       total_assigned = total_assigned + VALUES(total_assigned),
                       total_due = total_due + VALUES(total_due),
                       last_updated = NOW()";
        
        $balanceUpdateStmt = executeQuery($balanceUpdateSql, 'iidd', [$student['id'], $sessionId, $finalAmount, $finalAmount]);
        
        if ($balanceUpdateStmt === false) {
            throw new Exception('Failed to update balance: ' . $conn->error);
        }
        
        $assignedCount++;
        $totalAmount += $finalAmount; // Track total after discounts
    }
    
    logActivity(getCurrentUser()['id'], 'Assign Monthly Fees', 'Fees', 
                "Assigned fees for month: $month. Students: $assignedCount assigned, $skippedCount skipped");
    
    commitTransaction();
    
    $message = "Successfully assigned fees to <strong>$assignedCount students</strong>.<br>";
    $message .= "Total amount assigned: <strong>" . formatCurrency($totalAmount) . "</strong><br>";
    if ($skippedCount > 0) {
        $message .= "$skippedCount students were skipped (already assigned for this month).";
    }
    
    jsonResponse(true, $message);
    
} catch (Exception $e) {
    rollbackTransaction();
    error_log("Monthly Fee Assignment Error: " . $e->getMessage());
    jsonResponse(false, 'Error: ' . $e->getMessage() . ' Please check error logs for details.');
}

