<?php
// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$studentId = $data['student_id'] ?? 0;
$feeTypeId = $data['fee_type_id'] ?? 0;
$amount = $data['amount'] ?? 0;
$discount = $data['discount'] ?? 0;
$dueDate = $data['due_date'] ?? null;

if (empty($studentId) || empty($feeTypeId) || empty($amount)) {
    jsonResponse(false, 'All required fields must be filled');
}

// Check if student's class is graduated
$studentSql = "SELECT current_class_id FROM students WHERE id = ?";
$studentStmt = executeQuery($studentSql, 'i', [$studentId]);
$student = fetchOne($studentStmt);

if (!$student) {
    jsonResponse(false, 'Student not found');
}

if (!empty($student['current_class_id'])) {
    $graduationCheck = validateClassNotGraduated($student['current_class_id'], 'Invoice generation');
    if (!$graduationCheck['success']) {
        jsonResponse(false, $graduationCheck['message']);
    }
}

// Get current session
$session = getCurrentSession();
$sessionId = $session['id'] ?? 1;

// Generate invoice number
$sql = "SELECT MAX(id) as max_id FROM fee_invoices";
$result = executeQuery($sql);
$row = fetchOne($result);
$nextId = ($row['max_id'] ?? 0) + 1;
$invoiceNo = generateUniqueId(INVOICE_PREFIX, $nextId, 6);

// Calculate net amount
$netAmount = $amount - $discount;

// Create invoice
$sql = "INSERT INTO fee_invoices (invoice_no, student_id, session_id, total_amount, discount, net_amount, paid_amount, due_amount, due_date, status, generated_by)
        VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, 'Unpaid', ?)";

$stmt = executeQuery($sql, 'siiidddsi', [
    $invoiceNo, $studentId, $sessionId, $amount, $discount, $netAmount, $netAmount, $dueDate, getCurrentUser()['id']
]);

if ($stmt) {
    $invoiceId = getLastInsertId();
    
    // Add invoice item
    $itemSql = "INSERT INTO fee_invoice_items (invoice_id, fee_type_id, amount) VALUES (?, ?, ?)";
    executeQuery($itemSql, 'iid', [$invoiceId, $feeTypeId, $amount]);
    
    logActivity($currentUser['id'], 'Generate Invoice', 'Fees', "Generated invoice: $invoiceNo");
    jsonResponse(true, 'Invoice generated successfully! Invoice No: ' . $invoiceNo);
} else {
    jsonResponse(false, 'Failed to generate invoice');
}

