<?php
/**
 * AJAX: Get Student Fee Ledger
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$studentId = $_GET['student_id'] ?? null;
$sessionId = $_GET['session_id'] ?? null;

if (!$studentId) {
    jsonResponse(false, 'Student ID is required');
}

try {
    if (!$sessionId) {
        $currentSession = getCurrentSession();
        $sessionId = $currentSession['id'] ?? null;
    }
    
    // Check if student_fee_ledger table exists
    global $conn;
    $tableCheck = $conn->query("SHOW TABLES LIKE 'student_fee_ledger'");
    if ($tableCheck->num_rows == 0) {
        jsonResponse(false, 'Fee ledger table not found. Please run the database schema.');
    }
    
    $sql = "SELECT sfl.*, s.first_name, s.last_name
            FROM student_fee_ledger sfl
            INNER JOIN students s ON sfl.student_id = s.id
            WHERE sfl.student_id = ?";
    
    $params = [$studentId];
    $types = 'i';
    
    if ($sessionId) {
        $sql .= " AND sfl.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY sfl.transaction_date DESC, sfl.id DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $ledger = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($ledger as $entry) {
        $formatted[] = [
            'id' => $entry['id'],
            'student_id' => $entry['student_id'],
            'student_name' => trim($entry['first_name'] . ' ' . $entry['last_name']),
            'session_id' => $entry['session_id'],
            'transaction_type' => $entry['transaction_type'],
            'reference_type' => $entry['reference_type'],
            'reference_id' => $entry['reference_id'],
            'description' => $entry['description'],
            'debit' => $entry['debit_amount'] ?? 0,
            'credit' => $entry['credit_amount'] ?? 0,
            'balance' => $entry['balance'] ?? 0,
            'transaction_date' => $entry['transaction_date'] ?? $entry['created_at'],
            'created_at' => $entry['created_at'],
        ];
    }
    
    jsonResponse(true, 'Ledger loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load ledger: ' . $e->getMessage());
}

