<?php
/**
 * AJAX: Get Fee Invoices
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$studentId = $_GET['student_id'] ?? null;
$classId = $_GET['class_id'] ?? null;
$status = $_GET['status'] ?? null;
$sessionId = $_GET['session_id'] ?? null;

try {
    if (!$sessionId) {
        $currentSession = getCurrentSession();
        $sessionId = $currentSession['id'] ?? null;
    }
    
    $sql = "SELECT fi.*, s.first_name, s.last_name, s.student_id as admission_no
            FROM fee_invoices fi
            INNER JOIN students s ON fi.student_id = s.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($studentId) {
        $sql .= " AND fi.student_id = ?";
        $params[] = $studentId;
        $types .= 'i';
    }
    
    if ($classId) {
        $sql .= " AND s.current_class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($status) {
        $sql .= " AND fi.status = ?";
        $params[] = $status;
        $types .= 's';
    }
    
    if ($sessionId) {
        $sql .= " AND fi.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY fi.created_at DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $invoices = fetchAll($stmt);
    
    // Get invoice items for each invoice
    $formatted = [];
    foreach ($invoices as $invoice) {
        $itemsSql = "SELECT fii.*, ft.fee_name as fee_type_name
                     FROM fee_invoice_items fii
                     LEFT JOIN fee_types ft ON fii.fee_type_id = ft.id
                     WHERE fii.invoice_id = ?";
        $itemsStmt = executeQuery($itemsSql, 'i', [$invoice['id']]);
        $items = fetchAll($itemsStmt);
        
        $formattedItems = [];
        foreach ($items as $item) {
            $formattedItems[] = [
                'id' => $item['id'],
                'invoice_id' => $item['invoice_id'],
                'fee_type_id' => $item['fee_type_id'],
                'fee_type_name' => $item['fee_type_name'],
                'amount' => $item['amount'],
                'description' => $item['description'],
            ];
        }
        
        $formatted[] = [
            'id' => $invoice['id'],
            'invoice_no' => $invoice['invoice_no'],
            'student_id' => $invoice['student_id'],
            'student_name' => trim($invoice['first_name'] . ' ' . $invoice['last_name']),
            'session_id' => $invoice['session_id'],
            'total_amount' => $invoice['total_amount'],
            'discount' => $invoice['discount'],
            'net_amount' => $invoice['net_amount'],
            'paid_amount' => $invoice['paid_amount'],
            'due_amount' => $invoice['due_amount'],
            'due_date' => $invoice['due_date'],
            'status' => $invoice['status'],
            'created_at' => $invoice['created_at'],
            'updated_at' => $invoice['updated_at'],
            'items' => $formattedItems,
        ];
    }
    
    jsonResponse(true, 'Invoices loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load invoices: ' . $e->getMessage());
}

