<?php
/**
 * AJAX: Get Monthly Fee Assignments
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$studentId = $_GET['student_id'] ?? null;
$classId = $_GET['class_id'] ?? null;
$feeTypeId = $_GET['fee_type_id'] ?? null;
$month = $_GET['month'] ?? null;
$sessionId = $_GET['session_id'] ?? null;

try {
    if (!$sessionId) {
        $currentSession = getCurrentSession();
        $sessionId = $currentSession['id'] ?? null;
    }
    
    $sql = "SELECT mfa.*, s.first_name, s.last_name, s.student_id as admission_no,
            c.class_name, ft.fee_name as fee_type_name
            FROM monthly_fee_assignments mfa
            INNER JOIN students s ON mfa.student_id = s.id
            LEFT JOIN classes c ON mfa.class_id = c.id
            LEFT JOIN fee_types ft ON mfa.fee_type_id = ft.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($studentId) {
        $sql .= " AND mfa.student_id = ?";
        $params[] = $studentId;
        $types .= 'i';
    }
    
    if ($classId) {
        $sql .= " AND mfa.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($feeTypeId) {
        $sql .= " AND mfa.fee_type_id = ?";
        $params[] = $feeTypeId;
        $types .= 'i';
    }
    
    if ($month) {
        $sql .= " AND mfa.month = ?";
        $params[] = $month;
        $types .= 's';
    }
    
    if ($sessionId) {
        $sql .= " AND mfa.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY mfa.month DESC, s.first_name, s.last_name";
    
    $stmt = executeQuery($sql, $types, $params);
    $assignments = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($assignments as $assignment) {
        $formatted[] = [
            'id' => $assignment['id'],
            'student_id' => $assignment['student_id'],
            'student_name' => trim($assignment['first_name'] . ' ' . $assignment['last_name']),
            'student_id_number' => $assignment['admission_no'],
            'class_id' => $assignment['class_id'],
            'class_name' => $assignment['class_name'],
            'fee_type_id' => $assignment['fee_type_id'],
            'fee_type_name' => $assignment['fee_type_name'],
            'session_id' => $assignment['session_id'],
            'month' => $assignment['month'],
            'amount' => $assignment['amount'],
            'original_amount' => $assignment['original_amount'],
            'discount_amount' => $assignment['discount_amount'],
            'discount_type' => $assignment['discount_type'],
            'due_date' => $assignment['due_date'],
            'status' => $assignment['status'],
            'assigned_amount' => $assignment['assigned_amount'],
            'paid_amount' => $assignment['paid_amount'],
            'due_amount' => $assignment['due_amount'],
            'invoice_id' => $assignment['invoice_id'],
        ];
    }
    
    jsonResponse(true, 'Monthly assignments loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load monthly assignments: ' . $e->getMessage());
}

