<?php
/**
 * AJAX: Get Expense Records
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$branchId = $_GET['branch_id'] ?? null;
$startDate = $_GET['start_date'] ?? null;
$endDate = $_GET['end_date'] ?? null;

try {
    $sql = "SELECT e.*, b.branch_name, 
            u1.username as recorded_by_name, u2.username as approved_by_name
            FROM expenses e
            LEFT JOIN branches b ON e.branch_id = b.id
            LEFT JOIN users u1 ON e.recorded_by = u1.id
            LEFT JOIN users u2 ON e.approved_by = u2.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($branchId) {
        $sql .= " AND e.branch_id = ?";
        $params[] = $branchId;
        $types .= 'i';
    }
    
    if ($startDate) {
        $sql .= " AND e.expense_date >= ?";
        $params[] = $startDate;
        $types .= 's';
    }
    
    if ($endDate) {
        $sql .= " AND e.expense_date <= ?";
        $params[] = $endDate;
        $types .= 's';
    }
    
    $sql .= " ORDER BY e.expense_date DESC, e.created_at DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $expenses = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($expenses as $expense) {
        $formatted[] = [
            'id' => $expense['id'],
            'branch_id' => $expense['branch_id'],
            'branch_name' => $expense['branch_name'] ?? '',
            'expense_category' => $expense['expense_category'],
            'amount' => $expense['amount'],
            'expense_date' => $expense['expense_date'],
            'description' => $expense['description'],
            'payment_method' => $expense['payment_method'],
            'reference_no' => $expense['reference_no'],
            'receipt_file' => $expense['receipt_file'],
            'approved_by_name' => $expense['approved_by_name'],
            'recorded_by_name' => $expense['recorded_by_name'],
            'created_at' => $expense['created_at'],
        ];
    }
    
    jsonResponse(true, 'Expense records loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load expenses: ' . $e->getMessage());
}

