<?php
// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    $currentUser = getCurrentUser();
}

try {
    $sql = "SELECT * FROM fee_types ORDER BY fee_name";
    $feeTypes = fetchAll(executeQuery($sql));
    
    jsonResponse(true, 'Fee types loaded', $feeTypes);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load fee types: ' . $e->getMessage());
}

