<?php
/**
 * AJAX: Get Income Records
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$branchId = $_GET['branch_id'] ?? null;
$startDate = $_GET['start_date'] ?? null;
$endDate = $_GET['end_date'] ?? null;

try {
    $sql = "SELECT i.*, b.branch_name, u.username as recorded_by_name
            FROM income i
            LEFT JOIN branches b ON i.branch_id = b.id
            LEFT JOIN users u ON i.recorded_by = u.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($branchId) {
        $sql .= " AND i.branch_id = ?";
        $params[] = $branchId;
        $types .= 'i';
    }
    
    if ($startDate) {
        $sql .= " AND i.income_date >= ?";
        $params[] = $startDate;
        $types .= 's';
    }
    
    if ($endDate) {
        $sql .= " AND i.income_date <= ?";
        $params[] = $endDate;
        $types .= 's';
    }
    
    $sql .= " ORDER BY i.income_date DESC, i.created_at DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $income = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($income as $record) {
        $formatted[] = [
            'id' => $record['id'],
            'branch_id' => $record['branch_id'],
            'branch_name' => $record['branch_name'] ?? '',
            'income_category' => $record['income_category'],
            'amount' => $record['amount'],
            'income_date' => $record['income_date'],
            'description' => $record['description'],
            'payment_method' => $record['payment_method'],
            'reference_no' => $record['reference_no'],
            'recorded_by_name' => $record['recorded_by_name'],
            'created_at' => $record['created_at'],
        ];
    }
    
    jsonResponse(true, 'Income records loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load income: ' . $e->getMessage());
}

