<?php
/**
 * AJAX: Get Fee Payments
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$studentId = $_GET['student_id'] ?? null;
$invoiceId = $_GET['invoice_id'] ?? null;
$startDate = $_GET['start_date'] ?? null;
$endDate = $_GET['end_date'] ?? null;

try {
    $sql = "SELECT fp.*, s.first_name, s.last_name, s.student_id as admission_no,
            u.username as received_by_name
            FROM fee_payments fp
            INNER JOIN students s ON fp.student_id = s.id
            LEFT JOIN users u ON fp.received_by = u.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($studentId) {
        $sql .= " AND fp.student_id = ?";
        $params[] = $studentId;
        $types .= 'i';
    }
    
    if ($invoiceId) {
        $sql .= " AND fp.invoice_id = ?";
        $params[] = $invoiceId;
        $types .= 'i';
    }
    
    if ($startDate) {
        $sql .= " AND fp.payment_date >= ?";
        $params[] = $startDate;
        $types .= 's';
    }
    
    if ($endDate) {
        $sql .= " AND fp.payment_date <= ?";
        $params[] = $endDate;
        $types .= 's';
    }
    
    $sql .= " ORDER BY fp.payment_date DESC, fp.created_at DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $payments = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($payments as $payment) {
        $formatted[] = [
            'id' => $payment['id'],
            'receipt_no' => $payment['receipt_no'],
            'invoice_id' => $payment['invoice_id'],
            'student_id' => $payment['student_id'],
            'student_name' => trim($payment['first_name'] . ' ' . $payment['last_name']),
            'amount' => $payment['amount'],
            'payment_method' => $payment['payment_method'],
            'transaction_id' => $payment['transaction_id'],
            'payment_date' => $payment['payment_date'],
            'remarks' => $payment['remarks'],
            'received_by_name' => $payment['received_by_name'],
            'created_at' => $payment['created_at'],
        ];
    }
    
    jsonResponse(true, 'Payments loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load payments: ' . $e->getMessage());
}

