<?php
/**
 * AJAX: Get Finance Report
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin']);
}

$branchId = $_GET['branch_id'] ?? null;
$startDate = $_GET['start_date'] ?? null;
$endDate = $_GET['end_date'] ?? null;

try {
    // Calculate date range
    if (!$startDate) {
        $startDate = date('Y-m-01'); // First day of current month
    }
    if (!$endDate) {
        $endDate = date('Y-m-t'); // Last day of current month
    }
    
    // Total Income
    $incomeSql = "SELECT SUM(amount) as total FROM income WHERE income_date BETWEEN ? AND ?";
    $incomeParams = [$startDate, $endDate];
    if ($branchId) {
        $incomeSql .= " AND branch_id = ?";
        $incomeParams[] = $branchId;
    }
    $incomeStmt = executeQuery($incomeSql, $branchId ? 'ssi' : 'ss', $incomeParams);
    $incomeRow = fetchOne($incomeStmt);
    $totalIncome = $incomeRow['total'] ?? 0;
    
    // Total Expenses
    $expenseSql = "SELECT SUM(amount) as total FROM expenses WHERE expense_date BETWEEN ? AND ?";
    $expenseParams = [$startDate, $endDate];
    if ($branchId) {
        $expenseSql .= " AND branch_id = ?";
        $expenseParams[] = $branchId;
    }
    $expenseStmt = executeQuery($expenseSql, $branchId ? 'ssi' : 'ss', $expenseParams);
    $expenseRow = fetchOne($expenseStmt);
    $totalExpenses = $expenseRow['total'] ?? 0;
    
    // Net Profit
    $netProfit = $totalIncome - $totalExpenses;
    
    // Total Fee Collection
    $feeSql = "SELECT SUM(amount) as total FROM fee_payments WHERE payment_date BETWEEN ? AND ?";
    $feeParams = [$startDate, $endDate];
    $feeStmt = executeQuery($feeSql, 'ss', $feeParams);
    $feeRow = fetchOne($feeStmt);
    $totalFeeCollection = $feeRow['total'] ?? 0;
    
    // Pending Payments (from invoices)
    $pendingSql = "SELECT SUM(due_amount) as total FROM fee_invoices WHERE status != 'Paid'";
    $pendingStmt = executeQuery($pendingSql);
    $pendingRow = fetchOne($pendingStmt);
    $pendingPayments = $pendingRow['total'] ?? 0;
    
    // Invoice Statistics
    $invoiceStatsSql = "SELECT 
                        COUNT(*) as total,
                        SUM(CASE WHEN status = 'Paid' THEN 1 ELSE 0 END) as paid,
                        SUM(CASE WHEN status = 'Overdue' THEN 1 ELSE 0 END) as overdue
                        FROM fee_invoices";
    $invoiceStatsStmt = executeQuery($invoiceStatsSql);
    $invoiceStats = fetchOne($invoiceStatsStmt);
    
    // Monthly Summary
    $monthlySql = "SELECT 
                   DATE_FORMAT(income_date, '%Y-%m') as month,
                   SUM(CASE WHEN table_type = 'income' THEN amount ELSE 0 END) as income,
                   SUM(CASE WHEN table_type = 'expense' THEN amount ELSE 0 END) as expenses
                   FROM (
                       SELECT income_date, amount, 'income' as table_type FROM income
                       WHERE income_date BETWEEN ? AND ?
                       UNION ALL
                       SELECT expense_date, amount, 'expense' as table_type FROM expenses
                       WHERE expense_date BETWEEN ? AND ?
                   ) combined
                   GROUP BY DATE_FORMAT(income_date, '%Y-%m')
                   ORDER BY month DESC
                   LIMIT 12";
    $monthlyStmt = executeQuery($monthlySql, 'ssss', [$startDate, $endDate, $startDate, $endDate]);
    $monthlyData = fetchAll($monthlyStmt);
    
    $monthlySummary = [];
    foreach ($monthlyData as $month) {
        $income = $month['income'] ?? 0;
        $expenses = $month['expenses'] ?? 0;
        $monthlySummary[] = [
            'month' => $month['month'],
            'income' => $income,
            'expenses' => $expenses,
            'profit' => $income - $expenses,
        ];
    }
    
    // Income by Category
    $incomeCategorySql = "SELECT income_category, SUM(amount) as total
                          FROM income
                          WHERE income_date BETWEEN ? AND ?";
    $incomeCategoryParams = [$startDate, $endDate];
    if ($branchId) {
        $incomeCategorySql .= " AND branch_id = ?";
        $incomeCategoryParams[] = $branchId;
    }
    $incomeCategorySql .= " GROUP BY income_category ORDER BY total DESC";
    $incomeCategoryStmt = executeQuery($incomeCategorySql, $branchId ? 'ssi' : 'ss', $incomeCategoryParams);
    $incomeCategories = fetchAll($incomeCategoryStmt);
    
    $incomeByCategory = [];
    foreach ($incomeCategories as $cat) {
        $incomeByCategory[] = [
            'category' => $cat['income_category'],
            'amount' => $cat['total'],
        ];
    }
    
    // Expenses by Category
    $expenseCategorySql = "SELECT expense_category, SUM(amount) as total
                           FROM expenses
                           WHERE expense_date BETWEEN ? AND ?";
    $expenseCategoryParams = [$startDate, $endDate];
    if ($branchId) {
        $expenseCategorySql .= " AND branch_id = ?";
        $expenseCategoryParams[] = $branchId;
    }
    $expenseCategorySql .= " GROUP BY expense_category ORDER BY total DESC";
    $expenseCategoryStmt = executeQuery($expenseCategorySql, $branchId ? 'ssi' : 'ss', $expenseCategoryParams);
    $expenseCategories = fetchAll($expenseCategoryStmt);
    
    $expensesByCategory = [];
    foreach ($expenseCategories as $cat) {
        $expensesByCategory[] = [
            'category' => $cat['expense_category'],
            'amount' => $cat['total'],
        ];
    }
    
    $report = [
        'total_income' => $totalIncome,
        'total_expenses' => $totalExpenses,
        'net_profit' => $netProfit,
        'total_fee_collection' => $totalFeeCollection,
        'pending_payments' => $pendingPayments,
        'total_invoices' => $invoiceStats['total'] ?? 0,
        'paid_invoices' => $invoiceStats['paid'] ?? 0,
        'overdue_invoices' => $invoiceStats['overdue'] ?? 0,
        'monthly_summary' => $monthlySummary,
        'income_by_category' => $incomeByCategory,
        'expenses_by_category' => $expensesByCategory,
    ];
    
    jsonResponse(true, 'Finance report loaded', $report);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load finance report: ' . $e->getMessage());
}

