<?php
/**
 * AJAX: Get Fee Defaulters
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$classId = $_GET['class_id'] ?? null;
$feeTypeId = $_GET['fee_type_id'] ?? null;
$sessionId = $_GET['session_id'] ?? null;

try {
    if (!$sessionId) {
        $currentSession = getCurrentSession();
        $sessionId = $currentSession['id'] ?? null;
    }
    
    // Check if monthly_fee_assignments table exists
    global $conn;
    $tableCheck = $conn->query("SHOW TABLES LIKE 'monthly_fee_assignments'");
    if ($tableCheck->num_rows == 0) {
        jsonResponse(false, 'Monthly fee assignments table not found.');
    }
    
    $sql = "SELECT mfa.*, s.first_name, s.last_name, s.student_id as admission_no,
            c.class_name, ft.fee_name as fee_type_name
            FROM monthly_fee_assignments mfa
            INNER JOIN students s ON mfa.student_id = s.id
            LEFT JOIN classes c ON mfa.class_id = c.id
            LEFT JOIN fee_types ft ON mfa.fee_type_id = ft.id
            WHERE mfa.due_amount > 0
            AND (mfa.status = 'Assigned' OR mfa.status = 'Partially Paid' OR mfa.status = 'Overdue')";
    
    $params = [];
    $types = '';
    
    if ($classId) {
        $sql .= " AND mfa.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($feeTypeId) {
        $sql .= " AND mfa.fee_type_id = ?";
        $params[] = $feeTypeId;
        $types .= 'i';
    }
    
    if ($sessionId) {
        $sql .= " AND mfa.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY mfa.due_date ASC, mfa.due_amount DESC";
    
    $stmt = executeQuery($sql, $types, $params);
    $defaulters = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($defaulters as $defaulter) {
        // Check if overdue
        $isOverdue = false;
        if ($defaulter['due_date']) {
            $dueDate = new DateTime($defaulter['due_date']);
            $isOverdue = $dueDate < new DateTime();
        }
        
        $formatted[] = [
            'id' => $defaulter['id'],
            'student_id' => $defaulter['student_id'],
            'student_name' => trim($defaulter['first_name'] . ' ' . $defaulter['last_name']),
            'student_id_number' => $defaulter['admission_no'],
            'class_id' => $defaulter['class_id'],
            'class_name' => $defaulter['class_name'],
            'fee_type_id' => $defaulter['fee_type_id'],
            'fee_type_name' => $defaulter['fee_type_name'],
            'session_id' => $defaulter['session_id'],
            'month' => $defaulter['month'],
            'amount' => $defaulter['amount'],
            'original_amount' => $defaulter['original_amount'],
            'discount_amount' => $defaulter['discount_amount'],
            'discount_type' => $defaulter['discount_type'],
            'due_date' => $defaulter['due_date'],
            'status' => $isOverdue ? 'Overdue' : $defaulter['status'],
            'assigned_amount' => $defaulter['assigned_amount'],
            'paid_amount' => $defaulter['paid_amount'],
            'due_amount' => $defaulter['due_amount'],
            'invoice_id' => $defaulter['invoice_id'],
        ];
    }
    
    jsonResponse(true, 'Defaulters loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load defaulters: ' . $e->getMessage());
}

