<?php
/**
 * AJAX: Get Fee Structures
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$classId = $_GET['class_id'] ?? null;
$sessionId = $_GET['session_id'] ?? null;
$branchIdParam = $_GET['branch_id'] ?? null;

// Determine if user is Super Admin
$isSuperAdmin = ($currentUser['role_name'] ?? '') === 'Super Admin';

// Handle branch_id parameter for Super Admin
$branchId = null;
if ($isSuperAdmin) {
    // Only set branchId if it's not null and not empty string
    if ($branchIdParam !== null && $branchIdParam !== '' && $branchIdParam !== 'null') {
        $branchId = (int)$branchIdParam;
    } else {
        $branchId = null; // null means "All Branches"
    }
}

try {
    if (!$sessionId) {
        $currentSession = getCurrentSession();
        $sessionId = $currentSession['id'] ?? null;
    }
    
    $sql = "SELECT fs.*, c.class_name, ft.fee_name as fee_type_name, c.branch_id
            FROM fee_structures fs
            LEFT JOIN classes c ON fs.class_id = c.id
            LEFT JOIN fee_types ft ON fs.fee_type_id = ft.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($classId) {
        $sql .= " AND fs.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($sessionId) {
        $sql .= " AND fs.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    // Branch filter
    if ($isSuperAdmin) {
        // Super Admin can filter by branch_id or view all (null = all branches)
        if ($branchId !== null) {
            $sql .= " AND c.branch_id = ?";
            $params[] = $branchId;
            $types .= 'i';
        }
        // If branchId is null, don't add filter (shows all branches)
    } else {
        // Other roles are restricted to their assigned branch
        $userBranchId = $currentUser['branch_id'] ?? null;
        if ($userBranchId) {
            $sql .= " AND c.branch_id = ?";
            $params[] = $userBranchId;
            $types .= 'i';
        }
    }
    
    $sql .= " ORDER BY c.class_order, ft.fee_name";
    
    $stmt = executeQuery($sql, $types, $params);
    $structures = fetchAll($stmt);
    
    jsonResponse(true, 'Fee structures loaded', $structures);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load fee structures: ' . $e->getMessage());
}

