<?php
// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$invoiceId = $data['invoice_id'] ?? 0;
$amount = $data['amount'] ?? 0;
$paymentMethod = $data['payment_method'] ?? '';
$transactionId = sanitize($data['transaction_id'] ?? '');
$paymentDate = $data['payment_date'] ?? date('Y-m-d');
$remarks = sanitize($data['remarks'] ?? '');

if (empty($invoiceId) || empty($amount) || empty($paymentMethod)) {
    jsonResponse(false, 'All required fields must be filled');
}

beginTransaction();

try {
    // Get invoice details
    $sql = "SELECT * FROM fee_invoices WHERE id = ?";
    $stmt = executeQuery($sql, 'i', [$invoiceId]);
    $invoice = fetchOne($stmt);
    
    if (!$invoice) {
        jsonResponse(false, 'Invoice not found');
    }
    
    // Check if student's class is graduated
    $studentSql = "SELECT current_class_id FROM students WHERE id = ?";
    $studentStmt = executeQuery($studentSql, 'i', [$invoice['student_id']]);
    $student = fetchOne($studentStmt);
    
    if ($student && !empty($student['current_class_id'])) {
        $graduationCheck = validateClassNotGraduated($student['current_class_id'], 'Payment recording');
        if (!$graduationCheck['success']) {
            rollbackTransaction();
            jsonResponse(false, $graduationCheck['message']);
        }
    }
    
    if ($amount > $invoice['due_amount']) {
        jsonResponse(false, 'Payment amount cannot exceed due amount');
    }
    
    // Generate receipt number
    $sql = "SELECT MAX(id) as max_id FROM fee_payments";
    $result = executeQuery($sql);
    $row = fetchOne($result);
    $nextId = ($row['max_id'] ?? 0) + 1;
    $receiptNo = generateUniqueId(RECEIPT_PREFIX, $nextId, 6);
    
    // Record payment
    $sql = "INSERT INTO fee_payments (receipt_no, invoice_id, student_id, amount, payment_method, transaction_id, payment_date, remarks, received_by)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    $stmt = executeQuery($sql, 'siidssssi', [
        $receiptNo, $invoiceId, $invoice['student_id'], $amount, $paymentMethod, $transactionId, $paymentDate, $remarks, $currentUser['id']
    ]);
    
    // Update invoice
    $newPaidAmount = $invoice['paid_amount'] + $amount;
    $newDueAmount = $invoice['net_amount'] - $newPaidAmount;
    $newStatus = ($newDueAmount <= 0) ? 'Paid' : 'Partially Paid';
    
    $updateSql = "UPDATE fee_invoices SET paid_amount = ?, due_amount = ?, status = ? WHERE id = ?";
    executeQuery($updateSql, 'ddsi', [$newPaidAmount, $newDueAmount, $newStatus, $invoiceId]);
    
    // Get student and branch information for income entry
    $studentSql = "SELECT s.*, b.branch_id as student_branch_id FROM students s 
                   LEFT JOIN branches b ON s.branch_id = b.id 
                   WHERE s.id = ?";
    $studentStmt = executeQuery($studentSql, 'i', [$invoice['student_id']]);
    $student = fetchOne($studentStmt);
    
    // Get fee types from invoice items to determine income category
    $itemsSql = "SELECT ft.fee_name, ft.fee_code 
                 FROM fee_invoice_items ii
                 INNER JOIN fee_types ft ON ii.fee_type_id = ft.id
                 WHERE ii.invoice_id = ?
                 LIMIT 5";
    $itemsStmt = executeQuery($itemsSql, 'i', [$invoiceId]);
    $feeItems = fetchAll($itemsStmt);
    
    // Determine income category based on fee types
    $incomeCategory = 'Student Fees'; // Default
    if (!empty($feeItems)) {
        $feeNames = array_map(function($item) { return strtolower($item['fee_name']); }, $feeItems);
        $feeCodes = array_map(function($item) { return strtolower($item['fee_code']); }, $feeItems);
        
        if (in_array('tuition', $feeNames) || in_array('tuition fee', $feeNames) || in_array('tuition', $feeCodes)) {
            $incomeCategory = 'Tuition Fees';
        } elseif (in_array('examination', $feeNames) || in_array('exam', $feeNames) || in_array('examination', $feeCodes) || in_array('exam', $feeCodes)) {
            $incomeCategory = 'Examination Fees';
        } elseif (in_array('library', $feeNames) || in_array('library', $feeCodes)) {
            $incomeCategory = 'Library Fees';
        } elseif (in_array('transport', $feeNames) || in_array('transport', $feeCodes)) {
            $incomeCategory = 'Transport Fees';
        } elseif (in_array('hostel', $feeNames) || in_array('hostel', $feeCodes)) {
            $incomeCategory = 'Hostel Fees';
        } else {
            // Use first fee type name or default
            $incomeCategory = $feeItems[0]['fee_name'] ?? 'Student Fees';
        }
    }
    
    // Automatically create income entry
    $branchId = $student['branch_id'] ?? null;
    
    // If not super admin, use user's branch
    if (!hasRole(['Super Admin']) && empty($branchId)) {
        $branchId = $currentUser['branch_id'] ?? null;
    }
    
    $incomeDescription = "Fee payment - Receipt: $receiptNo, Invoice: {$invoice['invoice_no']}";
    if ($student) {
        $incomeDescription .= " - Student: " . htmlspecialchars($student['first_name'] . ' ' . $student['last_name']);
        if (!empty($student['student_id'])) {
            $incomeDescription .= " (ID: " . htmlspecialchars($student['student_id']) . ")";
        }
    }
    
    $referenceNo = 'PAY-' . $receiptNo;
    
    // Check if income already exists for this payment
    $checkIncomeSql = "SELECT id FROM income WHERE reference_no = ?";
    $checkIncomeStmt = executeQuery($checkIncomeSql, 's', [$referenceNo]);
    $existingIncome = fetchOne($checkIncomeStmt);
    
    if (!$existingIncome) {
        // Create income entry
        $incomeSql = "INSERT INTO income (branch_id, income_category, amount, income_date, payment_method, reference_no, description, recorded_by)
                     VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        $incomeStmt = executeQuery($incomeSql, 'isdssssi', [
            $branchId, 
            $incomeCategory, 
            $amount, 
            $paymentDate, 
            $paymentMethod, 
            $referenceNo, 
            $incomeDescription, 
            $currentUser['id']
        ]);
        
        if ($incomeStmt) {
            logActivity($currentUser['id'], 'Record Payment & Income', 'Fees', 
                       "Recorded payment and income: $receiptNo - " . formatCurrency($amount));
        }
    }
    
    logActivity($currentUser['id'], 'Record Payment', 'Fees', "Recorded payment: $receiptNo for invoice: {$invoice['invoice_no']}");
    
    commitTransaction();
    jsonResponse(true, 'Payment recorded successfully! Receipt No: ' . $receiptNo . '. Income entry created automatically.');
    
} catch (Exception $e) {
    rollbackTransaction();
    jsonResponse(false, 'Error: ' . $e->getMessage());
}

