<?php
/**
 * AJAX: Record Flexible Payment
 * 
 * Records payment with flexible allocation to multiple fee assignments
 * Supports partial payments, advance payments, and automatic allocation
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Accountant'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Accountant'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$studentId = (int)($data['student_id'] ?? 0);
$sessionId = (int)($data['session_id'] ?? 0);
$amount = (float)($data['amount'] ?? 0);
$paymentMethod = $data['payment_method'] ?? '';
$transactionId = sanitize($data['transaction_id'] ?? '');
$paymentDate = $data['payment_date'] ?? date('Y-m-d');
$remarks = sanitize($data['remarks'] ?? '');
$paymentType = $data['payment_type'] ?? 'normal';
$assignmentIdsJson = $data['assignment_ids'] ?? '[]';
$allocations = $data['allocations'] ?? null;

if (empty($studentId) || empty($sessionId) || $amount <= 0 || empty($paymentMethod)) {
    jsonResponse(false, 'All required fields must be filled');
}

beginTransaction();

try {
    // Generate receipt number
    $sql = "SELECT MAX(id) as max_id FROM fee_payments";
    $result = executeQuery($sql);
    $row = fetchOne($result);
    $nextId = ($row['max_id'] ?? 0) + 1;
    $receiptNo = generateUniqueId(RECEIPT_PREFIX, $nextId, 6);
    
    // Create a minimal invoice record for flexible payments (required by fee_payments table)
    $invoiceNo = 'FLEX-' . date('Ymd') . '-' . str_pad($nextId, 6, '0', STR_PAD_LEFT);
    $invoiceSql = "INSERT INTO fee_invoices 
                   (invoice_no, student_id, session_id, total_amount, discount, net_amount, paid_amount, due_amount, status, generated_by)
                   VALUES (?, ?, ?, ?, 0, ?, ?, 0, 'Paid', ?)";
    
    // Types: s=invoice_no, i=student_id, i=session_id, d=total_amount, d=net_amount, d=paid_amount, i=generated_by
    // 7 parameters: invoice_no, student_id, session_id, total_amount, net_amount, paid_amount, generated_by
    $invoiceStmt = executeQuery($invoiceSql, 'siidddi', [
        $invoiceNo, $studentId, $sessionId, $amount, $amount, $amount, $currentUser['id']
    ]);
    
    if ($invoiceStmt === false) {
        global $conn;
        throw new Exception('Failed to create invoice record: ' . $conn->error);
    }
    
    $invoiceId = getLastInsertId();
    
    // Create payment record
    $paymentSql = "INSERT INTO fee_payments 
                    (receipt_no, invoice_id, student_id, amount, payment_method, transaction_id, payment_date, remarks, received_by)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    // Types: s=receipt_no, i=invoice_id, i=student_id, d=amount, s=payment_method, s=transaction_id, s=payment_date, s=remarks, i=received_by
    $paymentStmt = executeQuery($paymentSql, 'siiddsssi', [
        $receiptNo, $invoiceId, $studentId, $amount, $paymentMethod, $transactionId, $paymentDate, $remarks, $currentUser['id']
    ]);
    
    if ($paymentStmt === false) {
        global $conn;
        throw new Exception('Failed to create payment record: ' . $conn->error);
    }
    
    $paymentId = getLastInsertId();
    $remainingAmount = $amount;
    $allocatedCount = 0;
    
    if ($paymentType === 'advance') {
        // Create advance credit
        $advanceSql = "INSERT INTO student_advance_credits 
                       (student_id, session_id, payment_id, amount, allocated_amount, available_amount, description)
                       VALUES (?, ?, ?, ?, 0, ?, ?)";
        
        $description = "Advance payment - Receipt: $receiptNo" . ($remarks ? " - $remarks" : '');
        $advanceStmt = executeQuery($advanceSql, 'iiidds', [
            $studentId, $sessionId, $paymentId, $amount, $amount, $description
        ]);
        
        if ($advanceStmt === false) {
            global $conn;
            throw new Exception('Failed to create advance credit: ' . $conn->error);
        }
        
        // Get current balance first
        $balanceSql = "SELECT balance FROM student_fee_ledger 
                       WHERE student_id = ? AND session_id = ? 
                       ORDER BY id DESC LIMIT 1";
        $balanceStmt = executeQuery($balanceSql, 'ii', [$studentId, $sessionId]);
        if ($balanceStmt === false) {
            global $conn;
            throw new Exception('Failed to get balance: ' . $conn->error);
        }
        
        $balanceRow = fetchOne($balanceStmt);
        $currentBalance = $balanceRow ? (float)$balanceRow['balance'] : 0.00;
        $newBalance = $currentBalance - $amount;
        
        // Update ledger
        $ledgerSql = "INSERT INTO student_fee_ledger 
                      (student_id, session_id, transaction_type, reference_id, reference_type, 
                       credit_amount, balance, description)
                      VALUES (?, ?, 'Advance Credit', ?, 'advance_credit', ?, ?, ?)";
        
        // Types: i=student_id, i=session_id, i=reference_id, d=credit_amount, d=balance, s=description
        $ledgerStmt = executeQuery($ledgerSql, 'iiidds', [
            $studentId, $sessionId, $paymentId, $amount, $newBalance, $description
        ]);
        
        if ($ledgerStmt === false) {
            global $conn;
            throw new Exception('Failed to update ledger: ' . $conn->error);
        }
        
        // Update balance
        $balanceUpdateSql = "INSERT INTO student_fee_balance 
                       (student_id, session_id, advance_credit, last_updated)
                       VALUES (?, ?, ?, NOW())
                       ON DUPLICATE KEY UPDATE 
                       advance_credit = advance_credit + VALUES(advance_credit),
                       last_updated = NOW()";
        
        $balanceUpdateStmt = executeQuery($balanceUpdateSql, 'iid', [$studentId, $sessionId, $amount]);
        
        if ($balanceUpdateStmt === false) {
            global $conn;
            throw new Exception('Failed to update balance: ' . $conn->error);
        }
        
    } else {
        // Get assignments to allocate
        $assignments = [];
        
        if ($paymentType === 'auto') {
            // Auto allocate to oldest fees first
            $autoSql = "SELECT * FROM monthly_fee_assignments 
                        WHERE student_id = ? AND session_id = ? AND due_amount > 0
                        ORDER BY month ASC, due_date ASC";
            $autoStmt = executeQuery($autoSql, 'ii', [$studentId, $sessionId]);
            if ($autoStmt === false) {
                global $conn;
                throw new Exception('Failed to fetch assignments: ' . $conn->error);
            }
            $assignments = fetchAll($autoStmt);
        } else {
            // Allocate to selected assignments
            $assignmentIds = json_decode($assignmentIdsJson, true);
            if (!empty($assignmentIds)) {
                $placeholders = implode(',', array_fill(0, count($assignmentIds), '?'));
                $selectedSql = "SELECT * FROM monthly_fee_assignments 
                                WHERE id IN ($placeholders) AND student_id = ? AND due_amount > 0
                                ORDER BY month ASC";
                $params = array_merge($assignmentIds, [$studentId]);
                $types = str_repeat('i', count($assignmentIds)) . 'i';
                $selectedStmt = executeQuery($selectedSql, $types, $params);
                if ($selectedStmt === false) {
                    global $conn;
                    throw new Exception('Failed to fetch selected assignments: ' . $conn->error);
                }
                $assignments = fetchAll($selectedStmt);
            }
        }
        
        // Get initial balance for payment allocation
        $initBalanceSql = "SELECT balance FROM student_fee_ledger 
                           WHERE student_id = ? AND session_id = ? 
                           ORDER BY id DESC LIMIT 1";
        $initBalanceStmt = executeQuery($initBalanceSql, 'ii', [$studentId, $sessionId]);
        if ($initBalanceStmt === false) {
            global $conn;
            throw new Exception('Failed to get initial balance: ' . $conn->error);
        }
        $initBalanceRow = fetchOne($initBalanceStmt);
        $runningBalance = $initBalanceRow ? (float)$initBalanceRow['balance'] : 0.00;
        
        // Allocate payment to assignments
        foreach ($assignments as $assignment) {
            if ($remainingAmount <= 0) break;
            
            $allocationAmount = min($remainingAmount, (float)$assignment['due_amount']);
            
            // Update assignment
            $newPaidAmount = (float)$assignment['paid_amount'] + $allocationAmount;
            $newDueAmount = (float)$assignment['due_amount'] - $allocationAmount;
            $newStatus = ($newDueAmount <= 0) ? 'Paid' : 'Partially Paid';
            
            $updateSql = "UPDATE monthly_fee_assignments 
                          SET paid_amount = ?, due_amount = ?, status = ? 
                          WHERE id = ?";
            $updateStmt = executeQuery($updateSql, 'ddsi', [$newPaidAmount, $newDueAmount, $newStatus, $assignment['id']]);
            
            if ($updateStmt === false) {
                global $conn;
                throw new Exception('Failed to update assignment: ' . $conn->error);
            }
            
            // Create payment allocation record
            $allocSql = "INSERT INTO payment_allocations 
                         (payment_id, allocation_type, reference_id, amount)
                         VALUES (?, 'Monthly Assignment', ?, ?)";
            $allocStmt = executeQuery($allocSql, 'iid', [$paymentId, $assignment['id'], $allocationAmount]);
            
            if ($allocStmt === false) {
                global $conn;
                throw new Exception('Failed to create allocation: ' . $conn->error);
            }
            
            // Update running balance
            $runningBalance -= $allocationAmount;
            
            // Update ledger
            $ledgerSql = "INSERT INTO student_fee_ledger 
                          (student_id, session_id, transaction_type, reference_id, reference_type, 
                           month, credit_amount, balance, description)
                          VALUES (?, ?, 'Payment', ?, 'payment', ?, ?, ?, ?)";
            
            $description = "Payment for " . date('F Y', strtotime($assignment['month'] . '-01')) . " - Receipt: $receiptNo";
            // Types: i=student_id, i=session_id, i=reference_id, s=month, d=credit_amount, d=balance, s=description
            $ledgerStmt = executeQuery($ledgerSql, 'iiisdds', [
                $studentId, $sessionId, $paymentId, $assignment['month'], $allocationAmount, $runningBalance, $description
            ]);
            
            if ($ledgerStmt === false) {
                global $conn;
                throw new Exception('Failed to update ledger: ' . $conn->error);
            }
            
            $remainingAmount -= $allocationAmount;
            $allocatedCount++;
        }
        
        // If there's remaining amount, create advance credit
        if ($remainingAmount > 0) {
            $advanceSql = "INSERT INTO student_advance_credits 
                           (student_id, session_id, payment_id, amount, allocated_amount, available_amount, description)
                           VALUES (?, ?, ?, ?, 0, ?, ?)";
            
            $description = "Excess payment from Receipt: $receiptNo" . ($remarks ? " - $remarks" : '');
            $advanceStmt = executeQuery($advanceSql, 'iiidds', [
                $studentId, $sessionId, $paymentId, $remainingAmount, $remainingAmount, $description
            ]);
            
            if ($advanceStmt === false) {
                global $conn;
                throw new Exception('Failed to create advance credit: ' . $conn->error);
            }
            
            // Update running balance for advance credit
            $runningBalance -= $remainingAmount;
            
            // Update ledger for advance
            $ledgerSql = "INSERT INTO student_fee_ledger 
                          (student_id, session_id, transaction_type, reference_id, reference_type, 
                           credit_amount, balance, description)
                          VALUES (?, ?, 'Advance Credit', ?, 'advance_credit', ?, ?, ?)";
            
            // Types: i=student_id, i=session_id, i=reference_id, d=credit_amount, d=balance, s=description
            $ledgerAdvanceStmt = executeQuery($ledgerSql, 'iiidds', [
                $studentId, $sessionId, $paymentId, $remainingAmount, $runningBalance, $description
            ]);
            
            if ($ledgerAdvanceStmt === false) {
                global $conn;
                throw new Exception('Failed to update ledger for advance: ' . $conn->error);
            }
        }
        
        // Update student fee balance - simplified to avoid subquery issues
        $paidAmount = $amount - $remainingAmount;
        
        // First get current totals
        $getTotalSql = "SELECT 
                        COALESCE(SUM(due_amount), 0) as total_due
                        FROM monthly_fee_assignments 
                        WHERE student_id = ? AND session_id = ?";
        $getTotalStmt = executeQuery($getTotalSql, 'ii', [$studentId, $sessionId]);
        if ($getTotalStmt === false) {
            global $conn;
            throw new Exception('Failed to get total due: ' . $conn->error);
        }
        $totalRow = fetchOne($getTotalStmt);
        $totalDue = $totalRow ? (float)$totalRow['total_due'] : 0.00;
        
        // Update balance
        $balanceSql = "INSERT INTO student_fee_balance 
                       (student_id, session_id, total_paid, total_due, advance_credit, last_updated)
                       VALUES (?, ?, ?, ?, ?, NOW())
                       ON DUPLICATE KEY UPDATE 
                       total_paid = total_paid + VALUES(total_paid),
                       total_due = VALUES(total_due),
                       advance_credit = advance_credit + VALUES(advance_credit),
                       last_updated = NOW()";
        
        $balanceUpdateStmt = executeQuery($balanceSql, 'iiddd', [
            $studentId, $sessionId, $paidAmount, $totalDue, $remainingAmount
        ]);
        
        if ($balanceUpdateStmt === false) {
            global $conn;
            throw new Exception('Failed to update balance: ' . $conn->error);
        }
    }
    
    // Get student and branch information for income entry
    $studentSql = "SELECT s.* FROM students s 
                   WHERE s.id = ?";
    $studentStmt = executeQuery($studentSql, 'i', [$studentId]);
    $student = fetchOne($studentStmt);
    
    // Determine income category based on allocated fee types
    $incomeCategory = 'Student Fees'; // Default
    
    if ($allocatedCount > 0 && isset($assignments) && !empty($assignments)) {
        // Get fee type IDs from allocated assignments
        $feeTypeIds = array_unique(array_column($assignments, 'fee_type_id'));
        
        if (!empty($feeTypeIds)) {
            // Get fee types from allocated assignments
            $placeholders = implode(',', array_fill(0, count($feeTypeIds), '?'));
            $feeTypesSql = "SELECT DISTINCT fee_name, fee_code 
                           FROM fee_types 
                           WHERE id IN ($placeholders)
                           LIMIT 5";
            $feeTypesStmt = executeQuery($feeTypesSql, str_repeat('i', count($feeTypeIds)), $feeTypeIds);
            $feeTypes = fetchAll($feeTypesStmt);
            
            if (!empty($feeTypes)) {
                $feeNames = array_map(function($ft) { return strtolower($ft['fee_name']); }, $feeTypes);
                $feeCodes = array_map(function($ft) { return strtolower($ft['fee_code']); }, $feeTypes);
                
                if (in_array('tuition', $feeNames) || in_array('tuition fee', $feeNames) || in_array('tuition', $feeCodes)) {
                    $incomeCategory = 'Tuition Fees';
                } elseif (in_array('examination', $feeNames) || in_array('exam', $feeNames) || in_array('examination', $feeCodes) || in_array('exam', $feeCodes)) {
                    $incomeCategory = 'Examination Fees';
                } elseif (in_array('library', $feeNames) || in_array('library', $feeCodes)) {
                    $incomeCategory = 'Library Fees';
                } elseif (in_array('transport', $feeNames) || in_array('transport', $feeCodes)) {
                    $incomeCategory = 'Transport Fees';
                } elseif (in_array('hostel', $feeNames) || in_array('hostel', $feeCodes)) {
                    $incomeCategory = 'Hostel Fees';
                } else {
                    $incomeCategory = $feeTypes[0]['fee_name'] ?? 'Student Fees';
                }
            }
        }
    }
    
    // Automatically create income entry
    $branchId = $student['branch_id'] ?? null;
    
    // If not super admin, use user's branch
    if (!hasRole(['Super Admin']) && empty($branchId)) {
        $branchId = $currentUser['branch_id'] ?? null;
    }
    
    $incomeDescription = "Flexible fee payment - Receipt: $receiptNo";
    if ($student) {
        $incomeDescription .= " - Student: " . htmlspecialchars($student['first_name'] . ' ' . $student['last_name']);
        if (!empty($student['student_id'])) {
            $incomeDescription .= " (ID: " . htmlspecialchars($student['student_id']) . ")";
        }
    }
    if ($allocatedCount > 0) {
        $incomeDescription .= " - Allocated to $allocatedCount fee assignment(s)";
    }
    
    $referenceNo = 'PAY-' . $receiptNo;
    
    // Check if income already exists for this payment
    $checkIncomeSql = "SELECT id FROM income WHERE reference_no = ?";
    $checkIncomeStmt = executeQuery($checkIncomeSql, 's', [$referenceNo]);
    $existingIncome = fetchOne($checkIncomeStmt);
    
    if (!$existingIncome) {
        // Create income entry
        $incomeSql = "INSERT INTO income (branch_id, income_category, amount, income_date, payment_method, reference_no, description, recorded_by)
                     VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        $incomeStmt = executeQuery($incomeSql, 'isdssssi', [
            $branchId, 
            $incomeCategory, 
            $amount, 
            $paymentDate, 
            $paymentMethod, 
            $referenceNo, 
            $incomeDescription, 
            $currentUser['id']
        ]);
        
        if ($incomeStmt) {
            logActivity($currentUser['id'], 'Record Flexible Payment & Income', 'Fees', 
                       "Recorded payment and income: $receiptNo - " . formatCurrency($amount));
        }
    }
    
    logActivity($currentUser['id'], 'Record Flexible Payment', 'Fees', 
                "Recorded payment: $receiptNo for student ID: $studentId. Amount: " . formatCurrency($amount));
    
    commitTransaction();
    
    $message = "Payment recorded successfully!<br>";
    $message .= "<strong>Receipt No:</strong> $receiptNo<br>";
    $message .= "<strong>Amount:</strong> " . formatCurrency($amount) . "<br>";
    if ($allocatedCount > 0) {
        $message .= "<strong>Allocated to:</strong> $allocatedCount fee assignment(s)<br>";
    }
    if ($remainingAmount > 0 && $paymentType !== 'advance') {
        $message .= "<strong>Advance Credit:</strong> " . formatCurrency($remainingAmount) . "<br>";
    }
    $message .= "<strong>Income entry created automatically.</strong>";
    
    jsonResponse(true, $message);
    
} catch (Exception $e) {
    rollbackTransaction();
    error_log("Flexible Payment Error: " . $e->getMessage());
    jsonResponse(false, 'Error: ' . $e->getMessage() . ' Please check error logs for details.');
}

