<?php
/**
 * AJAX: Add Hostel
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$hostelName = sanitize($data['name'] ?? $data['hostel_name'] ?? '');
$hostelType = 'Boys'; // Default, can be updated later
$address = sanitize($data['address'] ?? '');
$wardenName = sanitize($data['contact_person'] ?? '');
$wardenPhone = sanitize($data['contact_phone'] ?? '');

if (empty($hostelName)) {
    jsonResponse(false, 'Hostel name is required');
}

$branchId = $currentUser['branch_id'] ?? null;

$sql = "INSERT INTO hostels (hostel_name, hostel_type, address, warden_name, warden_phone, branch_id)
        VALUES (?, ?, ?, ?, ?, ?)";

$stmt = executeQuery($sql, 'sssssi', [
    $hostelName, $hostelType, $address, $wardenName, $wardenPhone, $branchId
]);

if ($stmt) {
    logActivity($currentUser['id'], 'Add Hostel', 'Facilities', "Added hostel: $hostelName");
    jsonResponse(true, 'Hostel added successfully!');
} else {
    jsonResponse(false, 'Failed to add hostel');
}
