<?php
/**
 * AJAX: Get Hostels
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

try {
    $sql = "SELECT h.*, b.branch_name,
            (SELECT COUNT(*) FROM hostel_rooms hr WHERE hr.hostel_id = h.id) as total_rooms,
            (SELECT COUNT(*) FROM hostel_rooms hr WHERE hr.hostel_id = h.id AND hr.occupied < hr.capacity) as available_rooms,
            (SELECT SUM(hr.capacity) FROM hostel_rooms hr WHERE hr.hostel_id = h.id) as total_capacity,
            (SELECT SUM(hr.occupied) FROM hostel_rooms hr WHERE hr.hostel_id = h.id) as occupied_capacity
            FROM hostels h
            LEFT JOIN branches b ON h.branch_id = b.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    // Branch filter
    if (!hasRole(['Super Admin']) && isset($currentUser['branch_id'])) {
        $sql .= " AND h.branch_id = ?";
        $params[] = $currentUser['branch_id'];
        $types .= 'i';
    }
    
    $sql .= " ORDER BY h.hostel_name";
    
    $stmt = !empty($params) ? executeQuery($sql, $types, $params) : executeQuery($sql);
    $hostels = fetchAll($stmt);
    
    // Format the data
    $formatted = [];
    foreach ($hostels as $hostel) {
        $formatted[] = [
            'id' => $hostel['id'],
            'hostel_name' => $hostel['hostel_name'],
            'description' => null, // Not in schema
            'address' => $hostel['address'],
            'contact_person' => $hostel['warden_name'],
            'contact_phone' => $hostel['warden_phone'],
            'contact_email' => null, // Not in schema
            'total_rooms' => $hostel['total_rooms'] ?? 0,
            'available_rooms' => $hostel['available_rooms'] ?? 0,
            'total_capacity' => $hostel['total_capacity'] ?? 0,
            'occupied_capacity' => $hostel['occupied_capacity'] ?? 0,
            'status' => 'Active', // Default
            'branch_id' => $hostel['branch_id'],
            'branch_name' => $hostel['branch_name'],
            'created_at' => $hostel['created_at'],
        ];
    }
    
    jsonResponse(true, 'Hostels loaded', $formatted);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load hostels: ' . $e->getMessage());
}

