<?php
// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    if (!hasRole(['Super Admin', 'Admin'])) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$examName = sanitize($data['exam_name'] ?? '');
$examTypeId = $data['exam_type_id'] ?? 0;
$classId = $data['class_id'] ?? 0;
$startDate = $data['start_date'] ?? '';
$endDate = $data['end_date'] ?? '';
$description = sanitize($data['description'] ?? '');

if (empty($examName) || empty($examTypeId) || empty($classId) || empty($startDate) || empty($endDate)) {
    jsonResponse(false, 'All required fields must be filled');
}

// Check if class is graduated
$graduationCheck = validateClassNotGraduated($classId, 'Exam creation');
if (!$graduationCheck['success']) {
    jsonResponse(false, $graduationCheck['message']);
}

// Get current session
$session = getCurrentSession();
$sessionId = $session['id'] ?? 1;

$sql = "INSERT INTO exams (exam_type_id, exam_name, class_id, session_id, start_date, end_date, description)
        VALUES (?, ?, ?, ?, ?, ?, ?)";

$stmt = executeQuery($sql, 'isiisss', [$examTypeId, $examName, $classId, $sessionId, $startDate, $endDate, $description]);

if ($stmt) {
    logActivity($currentUser['id'], 'Create Exam', 'Exams', "Created exam: $examName");
    jsonResponse(true, 'Exam created successfully!');
} else {
    jsonResponse(false, 'Failed to create exam');
}

