<?php
/**
 * AJAX: Add Exam Schedule
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    if (!hasRole(['Super Admin', 'Admin'])) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$examId = $data['exam_id'] ?? 0;
$subjectId = $data['subject_id'] ?? 0;
$examDate = $data['exam_date'] ?? '';
$startTime = $data['start_time'] ?? '';
$endTime = $data['end_time'] ?? '';
$roomNo = sanitize($data['room_no'] ?? '');
$totalMarks = $data['total_marks'] ?? 100;
$passingMarks = $data['passing_marks'] ?? 40;

if (empty($examId) || empty($subjectId) || empty($examDate) || empty($startTime) || empty($endTime)) {
    jsonResponse(false, 'All required fields must be filled');
}

// Get exam's class_id to check graduation status
$examSql = "SELECT class_id FROM exams WHERE id = ?";
$examStmt = executeQuery($examSql, 'i', [$examId]);
$exam = fetchOne($examStmt);

if (!$exam) {
    jsonResponse(false, 'Exam not found');
}

// Check if class is graduated
$graduationCheck = validateClassNotGraduated($exam['class_id'], 'Exam schedule management');
if (!$graduationCheck['success']) {
    jsonResponse(false, $graduationCheck['message']);
}

// Check if subject already scheduled
$checkSql = "SELECT id FROM exam_schedule WHERE exam_id = ? AND subject_id = ?";
$stmt = executeQuery($checkSql, 'ii', [$examId, $subjectId]);
if (fetchOne($stmt)) {
    jsonResponse(false, 'This subject is already scheduled for this exam');
}

$sql = "INSERT INTO exam_schedule (exam_id, subject_id, exam_date, start_time, end_time, room_no, total_marks, passing_marks)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = executeQuery($sql, 'iissssdd', [
    $examId, $subjectId, $examDate, $startTime, $endTime, $roomNo, $totalMarks, $passingMarks
]);

if ($stmt) {
    logActivity($currentUser['id'], 'Add Exam Schedule', 'Exams', "Added subject to exam schedule");
    jsonResponse(true, 'Subject added to exam schedule successfully!');
} else {
    jsonResponse(false, 'Failed to add to schedule');
}

