<?php
/**
 * AJAX: Get Exams
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    $currentUser = getCurrentUser();
}

$classId = $_GET['class_id'] ?? null;
$sessionId = $_GET['session_id'] ?? null;

try {
    $currentSession = getCurrentSession();
    if (!$sessionId && $currentSession) {
        $sessionId = $currentSession['id'];
    }
    
    $sql = "SELECT e.*, et.exam_name as exam_type_name, c.class_name
            FROM exams e
            LEFT JOIN exam_types et ON e.exam_type_id = et.id
            LEFT JOIN classes c ON e.class_id = c.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($classId) {
        $sql .= " AND e.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($sessionId) {
        $sql .= " AND e.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY e.start_date DESC, e.exam_name";
    
    $stmt = executeQuery($sql, $types, $params);
    $exams = fetchAll($stmt);
    
    jsonResponse(true, 'Exams loaded', $exams);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load exams: ' . $e->getMessage());
}

