<?php
/**
 * AJAX: Get Exam Schedules
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    $currentUser = getCurrentUser();
}

$examId = $_GET['exam_id'] ?? null;
$classId = $_GET['class_id'] ?? null;
$subjectId = $_GET['subject_id'] ?? null;

try {
    $sql = "SELECT es.*, e.exam_name, e.class_id, c.class_name,
            s.subject_name, s.subject_code
            FROM exam_schedule es
            INNER JOIN exams e ON es.exam_id = e.id
            LEFT JOIN classes c ON e.class_id = c.id
            LEFT JOIN subjects s ON es.subject_id = s.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($examId) {
        $sql .= " AND es.exam_id = ?";
        $params[] = $examId;
        $types .= 'i';
    }
    
    if ($classId) {
        $sql .= " AND e.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($subjectId) {
        $sql .= " AND es.subject_id = ?";
        $params[] = $subjectId;
        $types .= 'i';
    }
    
    $sql .= " ORDER BY es.exam_date, es.start_time";
    
    $stmt = executeQuery($sql, $types, $params);
    $schedules = fetchAll($stmt);
    
    jsonResponse(true, 'Exam schedules loaded', $schedules);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load exam schedules: ' . $e->getMessage());
}

