<?php
/**
 * AJAX: Get Exam Analytics
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin']);
}

$examId = $_GET['exam_id'] ?? null;
$classId = $_GET['class_id'] ?? null;

try {
    $currentSession = getCurrentSession();
    $sessionId = $currentSession['id'] ?? null;
    
    // Get exam statistics
    $sql = "SELECT COUNT(DISTINCT e.id) as total_exams,
            COUNT(DISTINCT CASE WHEN e.end_date < CURDATE() THEN e.id END) as completed_exams,
            COUNT(DISTINCT CASE WHEN e.end_date >= CURDATE() THEN e.id END) as pending_exams
            FROM exams e
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($examId) {
        $sql .= " AND e.id = ?";
        $params[] = $examId;
        $types .= 'i';
    }
    
    if ($classId) {
        $sql .= " AND e.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    if ($sessionId) {
        $sql .= " AND e.session_id = ?";
        $params[] = $sessionId;
        $types .= 'i';
    }
    
    $stmt = executeQuery($sql, $types, $params);
    $stats = fetchOne($stmt);
    
    // Get average marks and pass rate
    $marksSql = "SELECT 
                AVG(sm.marks_obtained) as avg_marks,
                COUNT(*) as total_entries,
                SUM(CASE WHEN sm.marks_obtained >= es.passing_marks THEN 1 ELSE 0 END) as passed
                FROM student_marks sm
                INNER JOIN exam_schedule es ON sm.exam_schedule_id = es.id
                INNER JOIN exams e ON es.exam_id = e.id
                WHERE sm.marks_obtained IS NOT NULL AND sm.is_absent = 0";
    
    $marksParams = [];
    $marksTypes = '';
    
    if ($examId) {
        $marksSql .= " AND e.id = ?";
        $marksParams[] = $examId;
        $marksTypes .= 'i';
    }
    
    if ($classId) {
        $marksSql .= " AND e.class_id = ?";
        $marksParams[] = $classId;
        $marksTypes .= 'i';
    }
    
    if ($sessionId) {
        $marksSql .= " AND e.session_id = ?";
        $marksParams[] = $sessionId;
        $marksTypes .= 'i';
    }
    
    $marksStmt = executeQuery($marksSql, $marksTypes, $marksParams);
    $marksStats = fetchOne($marksStmt);
    
    $averageMarks = $marksStats['avg_marks'] ?? 0;
    $passRate = ($marksStats['total_entries'] ?? 0) > 0 
        ? (($marksStats['passed'] ?? 0) / $marksStats['total_entries']) * 100 
        : 0;
    
    // Get class performance
    $classSql = "SELECT 
                e.class_id, c.class_name,
                AVG(sm.marks_obtained) as avg_marks,
                COUNT(DISTINCT sm.student_id) as total_students,
                SUM(CASE WHEN sm.marks_obtained >= es.passing_marks THEN 1 ELSE 0 END) as passed_students
                FROM student_marks sm
                INNER JOIN exam_schedule es ON sm.exam_schedule_id = es.id
                INNER JOIN exams e ON es.exam_id = e.id
                INNER JOIN classes c ON e.class_id = c.id
                WHERE sm.marks_obtained IS NOT NULL AND sm.is_absent = 0";
    
    $classParams = [];
    $classTypes = '';
    
    if ($examId) {
        $classSql .= " AND e.id = ?";
        $classParams[] = $examId;
        $classTypes .= 'i';
    }
    
    if ($sessionId) {
        $classSql .= " AND e.session_id = ?";
        $classParams[] = $sessionId;
        $classTypes .= 'i';
    }
    
    $classSql .= " GROUP BY e.class_id, c.class_name
                   ORDER BY avg_marks DESC";
    
    $classStmt = executeQuery($classSql, $classTypes, $classParams);
    $classPerformance = fetchAll($classStmt);
    
    $classResults = [];
    foreach ($classPerformance as $class) {
        $classPassRate = $class['total_students'] > 0 
            ? ($class['passed_students'] / $class['total_students']) * 100 
            : 0;
        
        $classResults[] = [
            'class_id' => $class['class_id'],
            'class_name' => $class['class_name'],
            'average_marks' => round($class['avg_marks'] ?? 0, 2),
            'pass_rate' => round($classPassRate, 2),
            'total_students' => $class['total_students'],
            'passed_students' => $class['passed_students'],
        ];
    }
    
    // Get subject performance
    $subjectSql = "SELECT 
                   es.subject_id, s.subject_name,
                   AVG(sm.marks_obtained) as avg_marks,
                   COUNT(DISTINCT sm.student_id) as total_students,
                   SUM(CASE WHEN sm.marks_obtained >= es.passing_marks THEN 1 ELSE 0 END) as passed_students
                   FROM student_marks sm
                   INNER JOIN exam_schedule es ON sm.exam_schedule_id = es.id
                   INNER JOIN exams e ON es.exam_id = e.id
                   INNER JOIN subjects s ON es.subject_id = s.id
                   WHERE sm.marks_obtained IS NOT NULL AND sm.is_absent = 0";
    
    $subjectParams = [];
    $subjectTypes = '';
    
    if ($examId) {
        $subjectSql .= " AND e.id = ?";
        $subjectParams[] = $examId;
        $subjectTypes .= 'i';
    }
    
    if ($classId) {
        $subjectSql .= " AND e.class_id = ?";
        $subjectParams[] = $classId;
        $subjectTypes .= 'i';
    }
    
    if ($sessionId) {
        $subjectSql .= " AND e.session_id = ?";
        $subjectParams[] = $sessionId;
        $subjectTypes .= 'i';
    }
    
    $subjectSql .= " GROUP BY es.subject_id, s.subject_name
                     ORDER BY avg_marks DESC";
    
    $subjectStmt = executeQuery($subjectSql, $subjectTypes, $subjectParams);
    $subjectPerformance = fetchAll($subjectStmt);
    
    $subjectResults = [];
    foreach ($subjectPerformance as $subject) {
        $subjectPassRate = $subject['total_students'] > 0 
            ? ($subject['passed_students'] / $subject['total_students']) * 100 
            : 0;
        
        $subjectResults[] = [
            'subject_id' => $subject['subject_id'],
            'subject_name' => $subject['subject_name'],
            'average_marks' => round($subject['avg_marks'] ?? 0, 2),
            'pass_rate' => round($subjectPassRate, 2),
            'total_students' => $subject['total_students'],
            'passed_students' => $subject['passed_students'],
        ];
    }
    
    $analytics = [
        'total_exams' => $stats['total_exams'] ?? 0,
        'completed_exams' => $stats['completed_exams'] ?? 0,
        'pending_exams' => $stats['pending_exams'] ?? 0,
        'average_marks' => round($averageMarks, 2),
        'pass_rate' => round($passRate, 2),
        'class_performance' => $classResults,
        'subject_performance' => $subjectResults,
    ];
    
    jsonResponse(true, 'Analytics loaded', $analytics);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load analytics: ' . $e->getMessage());
}

