<?php
/**
 * AJAX: Get Student Marks
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin', 'Teacher']);
}

$examScheduleId = $_GET['exam_schedule_id'] ?? null;

if (!$examScheduleId) {
    jsonResponse(false, 'Exam schedule ID is required');
}

try {
    // Get exam schedule details
    $scheduleSql = "SELECT es.*, e.class_id, c.class_name
                    FROM exam_schedule es
                    INNER JOIN exams e ON es.exam_id = e.id
                    LEFT JOIN classes c ON e.class_id = c.id
                    WHERE es.id = ?";
    $scheduleStmt = executeQuery($scheduleSql, 'i', [$examScheduleId]);
    $schedule = fetchOne($scheduleStmt);
    
    if (!$schedule) {
        jsonResponse(false, 'Exam schedule not found');
    }
    
    // Get all students in the class
    $studentsSql = "SELECT s.id, s.student_id as admission_no, s.first_name, s.last_name
                    FROM students s
                    WHERE s.current_class_id = ? AND s.status = 'Active'
                    ORDER BY s.first_name, s.last_name";
    $studentsStmt = executeQuery($studentsSql, 'i', [$schedule['class_id']]);
    $students = fetchAll($studentsStmt);
    
    // Get existing marks
    $marksSql = "SELECT sm.*, u.username as entered_by_name
                 FROM student_marks sm
                 LEFT JOIN users u ON sm.entered_by = u.id
                 WHERE sm.exam_schedule_id = ?";
    $marksStmt = executeQuery($marksSql, 'i', [$examScheduleId]);
    $marks = fetchAll($marksStmt);
    
    // Create marks map
    $marksMap = [];
    foreach ($marks as $mark) {
        $marksMap[$mark['student_id']] = $mark;
    }
    
    // Combine students with marks
    $result = [];
    foreach ($students as $student) {
        $mark = $marksMap[$student['id']] ?? null;
        
        $result[] = [
            'id' => $mark['id'] ?? null,
            'student_id' => $student['id'],
            'student_name' => trim($student['first_name'] . ' ' . $student['last_name']),
            'student_id_number' => $student['admission_no'],
            'exam_schedule_id' => $examScheduleId,
            'marks_obtained' => $mark['marks_obtained'] ?? null,
            'is_absent' => $mark['is_absent'] ?? 0,
            'remarks' => $mark['remarks'] ?? null,
            'entered_by' => $mark['entered_by'] ?? null,
            'entered_by_name' => $mark['entered_by_name'] ?? null,
            'entered_at' => $mark['entered_at'] ?? null,
            'updated_at' => $mark['updated_at'] ?? null,
        ];
    }
    
    jsonResponse(true, 'Marks loaded', $result);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load marks: ' . $e->getMessage());
}

