<?php
/**
 * AJAX: Save Exam Marks
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
        exit;
    }
    
    // Set session for compatibility
    $_SESSION['user_id'] = $currentUser['id'];
    $_SESSION['role_name'] = $currentUser['role_name'];
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
        exit;
    }
    if (!hasRole(['Super Admin', 'Admin', 'Teacher'])) {
        jsonResponse(false, 'Permission denied');
        exit;
    }
    $currentUser = getCurrentUser();
}

$isSuperAdmin = hasRole(['Super Admin']);
$isAdmin = hasRole(['Admin']);
$isTeacher = hasRole(['Teacher']);

$teacher = null;
$teacherId = null;
$currentSession = getCurrentSession();

if ($isTeacher && !$isSuperAdmin) {
    $teacher = getTeacherByUserId($currentUser['id']);
    if (!$teacher) {
        jsonResponse(false, 'Teacher profile not found. Please contact administrator.');
    }
    $teacherId = $teacher['id'];
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$scheduleId = $data['schedule_id'] ?? 0;
$students = $data['students'] ?? [];

if (empty($scheduleId) || empty($students)) {
    jsonResponse(false, 'Schedule ID and student data are required');
}

// Verify teacher has permission to enter marks for this schedule
if ($isTeacher && !$isSuperAdmin && $teacherId && $currentSession) {
    $verifySql = "SELECT es.id
                  FROM exam_schedule es
                  INNER JOIN subjects s ON es.subject_id = s.id
                  INNER JOIN exams e ON es.exam_id = e.id
                  INNER JOIN classes c ON e.class_id = c.id
                  INNER JOIN class_subjects cs ON s.id = cs.subject_id AND c.id = cs.class_id
                  WHERE es.id = ? AND cs.teacher_id = ? AND e.session_id = ?";
    $verifyStmt = executeQuery($verifySql, 'iii', [$scheduleId, $teacherId, $currentSession['id']]);
    $verified = fetchOne($verifyStmt);
    
    if (!$verified) {
        jsonResponse(false, 'You do not have permission to enter marks for this exam. This exam is not assigned to you.');
    }
}

// Get exam's class_id to check graduation status
$examClassSql = "SELECT e.class_id 
                 FROM exam_schedule es
                 INNER JOIN exams e ON es.exam_id = e.id
                 WHERE es.id = ?";
$examClassStmt = executeQuery($examClassSql, 'i', [$scheduleId]);
$examClass = fetchOne($examClassStmt);

if ($examClass) {
    $graduationCheck = validateClassNotGraduated($examClass['class_id'], 'Exam marks entry');
    if (!$graduationCheck['success']) {
        jsonResponse(false, $graduationCheck['message']);
    }
}

beginTransaction();

try {
    $savedCount = 0;
    $currentUserId = $currentUser['id'];
    
    foreach ($students as $studentData) {
        $studentId = $studentData['id'] ?? 0;
        $marks = $studentData['marks'] ?? null;
        $isAbsent = isset($studentData['is_absent']) ? 1 : 0;
        $remarks = sanitize($studentData['remarks'] ?? '');
        
        if (empty($studentId)) continue;
        
        // If absent, marks should be null
        if ($isAbsent) {
            $marks = null;
        }
        
        // Check if marks already exist
        $checkSql = "SELECT id FROM student_marks WHERE student_id = ? AND exam_schedule_id = ?";
        $checkStmt = executeQuery($checkSql, 'ii', [$studentId, $scheduleId]);
        $existing = fetchOne($checkStmt);
        
        if ($existing) {
            // Update existing
            $sql = "UPDATE student_marks 
                    SET marks_obtained = ?, is_absent = ?, remarks = ?, entered_by = ?
                    WHERE student_id = ? AND exam_schedule_id = ?";
            executeQuery($sql, 'dissii', [$marks, $isAbsent, $remarks, $currentUserId, $studentId, $scheduleId]);
        } else {
            // Insert new
            $sql = "INSERT INTO student_marks 
                    (student_id, exam_schedule_id, marks_obtained, is_absent, remarks, entered_by)
                    VALUES (?, ?, ?, ?, ?, ?)";
            executeQuery($sql, 'iidisi', [$studentId, $scheduleId, $marks, $isAbsent, $remarks, $currentUserId]);
        }
        
        $savedCount++;
    }
    
    logActivity($currentUserId, 'Enter Exam Marks', 'Exams', "Entered marks for $savedCount students");
    
    commitTransaction();
    jsonResponse(true, "Marks saved successfully for $savedCount students!");
    
} catch (Exception $e) {
    rollbackTransaction();
    jsonResponse(false, 'Error: ' . $e->getMessage());
}

