<?php
/**
 * AJAX: Get All Students
 * 
 * Fetch all students with optional filters (status, class, section, search, branch)
 * Supports both web session and Flutter/mobile app authentication
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$isSuperAdmin = false;
$branchFilter = '';

$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $isSuperAdmin = ($currentUser['role_name'] ?? '') === 'Super Admin';
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    $isSuperAdmin = hasRole(['Super Admin']);
}

// Get branch filter
$branchId = null;
if ($isSuperAdmin) {
    // Super Admin can filter by branch or view all
    $branchIdParam = $_GET['branch_id'] ?? null;
    // Only set branchId if it's not null and not empty string
    if ($branchIdParam !== null && $branchIdParam !== '' && $branchIdParam !== 'null') {
        $branchId = (int)$branchIdParam;
    } else {
        $branchId = null; // null means "All Branches"
    }
} else {
    // Other roles restricted to their branch
    $branchId = $currentUser['branch_id'] ?? null;
}

try {
    // Get filter parameters
    $status = $_GET['status'] ?? null;
    $classId = $_GET['class_id'] ?? null;
    $sectionId = $_GET['section_id'] ?? null;
    $search = $_GET['search'] ?? null;
    
    // Build SQL query
    $sql = "SELECT s.id, s.student_id, s.admission_no, s.first_name, s.last_name, s.middle_name,
            s.email, s.phone, s.current_class_id, s.current_section_id, s.status, s.photo,
            c.class_name, sec.section_name, b.branch_name
            FROM students s
            LEFT JOIN classes c ON s.current_class_id = c.id
            LEFT JOIN sections sec ON s.current_section_id = sec.id
            LEFT JOIN branches b ON s.branch_id = b.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    // Apply branch filter
    if ($branchId) {
        $sql .= " AND s.branch_id = ?";
        $params[] = $branchId;
        $types .= 'i';
    }
    
    // Apply status filter
    if ($status) {
        $sql .= " AND s.status = ?";
        $params[] = $status;
        $types .= 's';
    }
    
    // Apply class filter
    if ($classId) {
        $sql .= " AND s.current_class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    // Apply section filter
    if ($sectionId) {
        $sql .= " AND s.current_section_id = ?";
        $params[] = $sectionId;
        $types .= 'i';
    }
    
    // Apply search filter
    if ($search && !empty(trim($search))) {
        $searchTerm = '%' . trim($search) . '%';
        $sql .= " AND (s.first_name LIKE ? OR s.last_name LIKE ? OR s.student_id LIKE ? OR s.admission_no LIKE ?)";
        $params[] = $searchTerm;
        $params[] = $searchTerm;
        $params[] = $searchTerm;
        $params[] = $searchTerm;
        $types .= 'ssss';
    }
    
    $sql .= " ORDER BY s.first_name, s.last_name";
    
    // Execute query
    if (!empty($params)) {
        $stmt = executeQuery($sql, $types, $params);
    } else {
        $stmt = executeQuery($sql);
    }
    
    $students = fetchAll($stmt);
    
    // Format response data
    $formattedStudents = [];
    foreach ($students as $student) {
        $formattedStudents[] = [
            'id' => (int)$student['id'],
            'student_id' => $student['student_id'] ?? '',
            'admission_no' => $student['admission_no'] ?? '',
            'first_name' => $student['first_name'] ?? '',
            'last_name' => $student['last_name'] ?? '',
            'middle_name' => $student['middle_name'] ?? null,
            'email' => $student['email'] ?? null,
            'phone' => $student['phone'] ?? null,
            'current_class_id' => $student['current_class_id'] ? (int)$student['current_class_id'] : null,
            'class_name' => $student['class_name'] ?? null,
            'current_section_id' => $student['current_section_id'] ? (int)$student['current_section_id'] : null,
            'section_name' => $student['section_name'] ?? null,
            'status' => $student['status'] ?? 'Active',
            'photo' => $student['photo'] ?? null,
            'branch_name' => $student['branch_name'] ?? null,
        ];
    }
    
    jsonResponse(true, 'Students loaded successfully', $formattedStudents);
    
} catch (Exception $e) {
    error_log('Get all students error: ' . $e->getMessage());
    jsonResponse(false, 'Failed to load students: ' . $e->getMessage());
}

