<?php
/**
 * AJAX: Get Student Attendance
 * 
 * Get attendance records for students in a class/section for a specific date
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$classId = $_GET['class_id'] ?? null;
$sectionId = $_GET['section_id'] ?? null;
$date = $_GET['date'] ?? date('Y-m-d');
$subjectId = $_GET['subject_id'] ?? null;

if (!$classId || !$sectionId) {
    jsonResponse(false, 'Class and section are required');
}

try {
    // Get all students in the class-section
    $studentsSql = "SELECT s.id, s.student_id, s.first_name, s.last_name, s.current_class_id, s.current_section_id
                    FROM students s
                    WHERE s.current_class_id = ? AND s.current_section_id = ? AND s.status = 'Active'
                    ORDER BY s.first_name, s.last_name";
    $studentsStmt = executeQuery($studentsSql, 'ii', [$classId, $sectionId]);
    $students = fetchAll($studentsStmt);
    
    // Get existing attendance records for the date
    $attendanceSql = "SELECT sa.*, u.username as marked_by_name
                      FROM student_attendance sa
                      LEFT JOIN users u ON sa.marked_by = u.id
                      WHERE sa.class_id = ? AND sa.section_id = ? AND sa.attendance_date = ?";
    $attendanceParams = [$classId, $sectionId, $date];
    $attendanceTypes = 'iis';
    
    if ($subjectId) {
        $attendanceSql .= " AND sa.subject_id = ?";
        $attendanceParams[] = $subjectId;
        $attendanceTypes .= 'i';
    }
    
    $attendanceStmt = executeQuery($attendanceSql, $attendanceTypes, $attendanceParams);
    $attendanceRecords = fetchAll($attendanceStmt);
    
    // Create a map of student_id => attendance record
    $attendanceMap = [];
    foreach ($attendanceRecords as $record) {
        $attendanceMap[$record['student_id']] = $record;
    }
    
    // Get class and section names
    $classSql = "SELECT class_name FROM classes WHERE id = ?";
    $classStmt = executeQuery($classSql, 'i', [$classId]);
    $classData = fetchOne($classStmt);
    $className = $classData['class_name'] ?? '';
    
    $sectionSql = "SELECT section_name FROM sections WHERE id = ?";
    $sectionStmt = executeQuery($sectionSql, 'i', [$sectionId]);
    $sectionData = fetchOne($sectionStmt);
    $sectionName = $sectionData['section_name'] ?? '';
    
    // Get subject name if provided
    $subjectName = null;
    if ($subjectId) {
        $subjectSql = "SELECT subject_name FROM subjects WHERE id = ?";
        $subjectStmt = executeQuery($subjectSql, 'i', [$subjectId]);
        $subjectData = fetchOne($subjectStmt);
        $subjectName = $subjectData['subject_name'] ?? null;
    }
    
    // Combine students with their attendance records
    $result = [];
    foreach ($students as $student) {
        $attendance = $attendanceMap[$student['id']] ?? null;
        
        $result[] = [
            'id' => $attendance['id'] ?? null,
            'student_id' => $student['id'],
            'student_name' => trim($student['first_name'] . ' ' . $student['last_name']),
            'student_id_number' => $student['student_id'],
            'class_id' => $classId,
            'class_name' => $className,
            'section_id' => $sectionId,
            'section_name' => $sectionName,
            'subject_id' => $subjectId,
            'subject_name' => $subjectName,
            'attendance_date' => $date,
            'status' => $attendance['status'] ?? 'Present',
            'remarks' => $attendance['remarks'] ?? null,
            'marked_by' => $attendance['marked_by'] ?? null,
            'marked_by_name' => $attendance['marked_by_name'] ?? null,
            'created_at' => $attendance['created_at'] ?? date('Y-m-d H:i:s'),
        ];
    }
    
    jsonResponse(true, 'Attendance loaded', $result);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load attendance: ' . $e->getMessage());
}

