<?php
/**
 * AJAX: Get Attendance History
 * 
 * Get attendance history for a student or class
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
}

$studentId = $_GET['student_id'] ?? null;
$classId = $_GET['class_id'] ?? null;
$startDate = $_GET['start_date'] ?? date('Y-m-01');
$endDate = $_GET['end_date'] ?? date('Y-m-t');

try {
    $sql = "SELECT sa.*, 
            s.first_name, s.last_name, s.student_id as student_id_number,
            c.class_name, sec.section_name,
            sub.subject_name,
            u.username as marked_by_name
            FROM student_attendance sa
            LEFT JOIN students s ON sa.student_id = s.id
            LEFT JOIN classes c ON sa.class_id = c.id
            LEFT JOIN sections sec ON sa.section_id = sec.id
            LEFT JOIN subjects sub ON sa.subject_id = sub.id
            LEFT JOIN users u ON sa.marked_by = u.id
            WHERE 1=1";
    
    $params = [];
    $types = '';
    
    if ($studentId) {
        $sql .= " AND sa.student_id = ?";
        $params[] = $studentId;
        $types .= 'i';
    }
    
    if ($classId) {
        $sql .= " AND sa.class_id = ?";
        $params[] = $classId;
        $types .= 'i';
    }
    
    $sql .= " AND sa.attendance_date BETWEEN ? AND ?
             ORDER BY sa.attendance_date DESC, s.first_name, s.last_name";
    $params[] = $startDate;
    $params[] = $endDate;
    $types .= 'ss';
    
    $stmt = executeQuery($sql, $types, $params);
    $history = fetchAll($stmt);
    
    // Format the results
    $result = [];
    foreach ($history as $record) {
        $result[] = [
            'id' => $record['id'],
            'student_id' => $record['student_id'],
            'student_name' => trim(($record['first_name'] ?? '') . ' ' . ($record['last_name'] ?? '')),
            'student_id_number' => $record['student_id_number'],
            'class_id' => $record['class_id'],
            'class_name' => $record['class_name'],
            'section_id' => $record['section_id'],
            'section_name' => $record['section_name'],
            'subject_id' => $record['subject_id'],
            'subject_name' => $record['subject_name'],
            'attendance_date' => $record['attendance_date'],
            'status' => $record['status'],
            'remarks' => $record['remarks'],
            'marked_by' => $record['marked_by'],
            'marked_by_name' => $record['marked_by_name'],
            'created_at' => $record['created_at'],
        ];
    }
    
    jsonResponse(true, 'History loaded', $result);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load history: ' . $e->getMessage());
}

