<?php
/**
 * AJAX: Get Staff Attendance
 * 
 * Get attendance records for all staff for a specific date
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_GET['user_id'] ?? $_POST['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) {
        jsonResponse(false, 'Unauthorized');
    }
    $currentUser = getCurrentUser();
    requireRole(['Super Admin', 'Admin']);
}

$date = $_GET['date'] ?? date('Y-m-d');

try {
    // Get all active staff
    $staffSql = "SELECT s.id, s.staff_id, s.first_name, s.last_name, s.is_active
                 FROM staff s
                 WHERE s.is_active = 1
                 ORDER BY s.first_name, s.last_name";
    $staffStmt = executeQuery($staffSql);
    $staffList = fetchAll($staffStmt);
    
    // Get existing attendance records for the date
    $attendanceSql = "SELECT sa.*, u.username as marked_by_name
                      FROM staff_attendance sa
                      LEFT JOIN users u ON sa.marked_by = u.id
                      WHERE sa.attendance_date = ?";
    $attendanceStmt = executeQuery($attendanceSql, 's', [$date]);
    $attendanceRecords = fetchAll($attendanceStmt);
    
    // Create a map of staff_id => attendance record
    $attendanceMap = [];
    foreach ($attendanceRecords as $record) {
        $attendanceMap[$record['staff_id']] = $record;
    }
    
    // Combine staff with their attendance records
    $result = [];
    foreach ($staffList as $staff) {
        $attendance = $attendanceMap[$staff['id']] ?? null;
        
        $result[] = [
            'id' => $attendance['id'] ?? null,
            'staff_id' => $staff['id'],
            'staff_name' => trim($staff['first_name'] . ' ' . $staff['last_name']),
            'staff_id_number' => $staff['staff_id'],
            'attendance_date' => $date,
            'check_in' => $attendance['check_in'] ?? null,
            'check_out' => $attendance['check_out'] ?? null,
            'status' => $attendance['status'] ?? 'Present',
            'remarks' => $attendance['remarks'] ?? null,
            'marked_by' => $attendance['marked_by'] ?? null,
            'marked_by_name' => $attendance['marked_by_name'] ?? null,
            'created_at' => $attendance['created_at'] ?? date('Y-m-d H:i:s'),
        ];
    }
    
    jsonResponse(true, 'Staff attendance loaded', $result);
    
} catch (Exception $e) {
    jsonResponse(false, 'Failed to load staff attendance: ' . $e->getMessage());
}

