<?php
/**
 * AJAX: Save Staff Attendance
 * 
 * @author School ERP Development Team
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$date = $data['date'] ?? '';
$staff = $data['staff'] ?? [];

if (empty($date) || empty($staff)) {
    jsonResponse(false, 'Date and staff data are required');
}

beginTransaction();

try {
    $savedCount = 0;
    $currentUserId = $currentUser['id'];
    
    foreach ($staff as $staffData) {
        $staffId = $staffData['id'] ?? $staffData['staff_id'] ?? 0;
        $status = $staffData['status'] ?? 'Present';
        $checkIn = $staffData['check_in'] ?? null;
        $checkOut = $staffData['check_out'] ?? null;
        $remarks = sanitize($staffData['remarks'] ?? '');
        
        if (empty($staffId)) continue;
        
        // Check if attendance already exists
        $checkSql = "SELECT id FROM staff_attendance WHERE staff_id = ? AND attendance_date = ?";
        $checkStmt = executeQuery($checkSql, 'is', [$staffId, $date]);
        $existing = fetchOne($checkStmt);
        
        if ($existing) {
            // Update existing
            $sql = "UPDATE staff_attendance 
                    SET status = ?, check_in = ?, check_out = ?, remarks = ?, marked_by = ?
                    WHERE staff_id = ? AND attendance_date = ?";
            executeQuery($sql, 'ssssiis', [$status, $checkIn, $checkOut, $remarks, $currentUserId, $staffId, $date]);
        } else {
            // Insert new
            $sql = "INSERT INTO staff_attendance 
                    (staff_id, attendance_date, status, check_in, check_out, remarks, marked_by)
                    VALUES (?, ?, ?, ?, ?, ?, ?)";
            executeQuery($sql, 'isssssi', [$staffId, $date, $status, $checkIn, $checkOut, $remarks, $currentUserId]);
        }
        
        $savedCount++;
    }
    
    logActivity($currentUserId, 'Mark Staff Attendance', 'Attendance', "Marked attendance for $savedCount staff on $date");
    
    commitTransaction();
    jsonResponse(true, "Attendance saved for $savedCount staff members!");
    
} catch (Exception $e) {
    rollbackTransaction();
    jsonResponse(false, 'Error: ' . $e->getMessage());
}

