<?php
/**
 * AJAX: Save Student Attendance
 * 
 * Save attendance records for multiple students
 * 
 * @author School ERP Development Team
 * @version 1.0.0
 */

// Start output buffering FIRST to catch any unwanted output
ob_start();

require_once '../../config/config.php';

// NOW suppress error display AFTER config is loaded
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Clear any output that might have been generated by config.php
ob_clean();

// Set JSON header early
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-cache, must-revalidate');

// Support both session-based (web) and user_id parameter (Flutter/mobile) authentication
$currentUser = null;
$userId = $_POST['user_id'] ?? json_decode(file_get_contents('php://input'), true)['user_id'] ?? null;

if ($userId) {
    // Flutter/mobile app authentication
    $sql = "SELECT u.*, r.role_name, b.branch_name 
            FROM users u 
            LEFT JOIN roles r ON u.role_id = r.id 
            LEFT JOIN branches b ON u.branch_id = b.id 
            WHERE u.id = ? AND u.is_active = 1";
    $stmt = executeQuery($sql, 'i', [$userId]);
    $currentUser = fetchOne($stmt);
    
    if (!$currentUser) {
        jsonResponse(false, 'Invalid user ID');
    }
    
    $allowedRoles = ['Super Admin', 'Admin', 'Teacher'];
    if (!in_array($currentUser['role_name'], $allowedRoles)) {
        jsonResponse(false, 'Permission denied');
    }
} else {
    // Web session-based authentication
    if (!isLoggedIn()) jsonResponse(false, 'Unauthorized');
    if (!hasRole(['Super Admin', 'Admin', 'Teacher'])) jsonResponse(false, 'Permission denied');
    $currentUser = getCurrentUser();
}

$input = file_get_contents('php://input');
$data = json_decode($input, true);

if (!$data) {
    $data = $_POST;
}

$date = $data['date'] ?? '';
$classId = $data['class_id'] ?? 0;
$sectionId = $data['section_id'] ?? 0;
$students = $data['students'] ?? [];
$subjectId = $data['subject_id'] ?? null;

if (empty($date) || empty($classId) || empty($sectionId) || empty($students)) {
    jsonResponse(false, 'All fields are required');
}

// Check if class is graduated
$graduationCheck = validateClassNotGraduated($classId, 'Attendance marking');
if (!$graduationCheck['success']) {
    jsonResponse(false, $graduationCheck['message']);
}

beginTransaction();

try {
    $savedCount = 0;
    $currentUserId = $currentUser['id'];
    
    foreach ($students as $studentData) {
        $studentId = $studentData['id'] ?? $studentData['student_id'] ?? 0;
        $status = $studentData['status'] ?? 'Present';
        $remarks = sanitize($studentData['remarks'] ?? '');
        
        if (empty($studentId)) continue;
        
        // Check if attendance already exists
        $checkSql = "SELECT id FROM student_attendance 
                     WHERE student_id = ? AND attendance_date = ?";
        $checkParams = [$studentId, $date];
        $checkTypes = 'is';
        
        if ($subjectId) {
            $checkSql .= " AND subject_id = ?";
            $checkParams[] = $subjectId;
            $checkTypes .= 'i';
        }
        
        $checkStmt = executeQuery($checkSql, $checkTypes, $checkParams);
        $existing = fetchOne($checkStmt);
        
        if ($existing) {
            // Update existing
            $sql = "UPDATE student_attendance 
                    SET status = ?, remarks = ?, marked_by = ?";
            $updateParams = [$status, $remarks, $currentUserId];
            $updateTypes = 'ssi';
            
            if ($subjectId) {
                $sql .= ", subject_id = ?";
                $updateParams[] = $subjectId;
                $updateTypes .= 'i';
            }
            
            $sql .= " WHERE student_id = ? AND attendance_date = ?";
            $updateParams[] = $studentId;
            $updateParams[] = $date;
            $updateTypes .= 'is';
            
            if ($subjectId) {
                $sql .= " AND subject_id = ?";
                $updateParams[] = $subjectId;
                $updateTypes .= 'i';
            }
            
            executeQuery($sql, $updateTypes, $updateParams);
        } else {
            // Insert new
            $sql = "INSERT INTO student_attendance 
                    (student_id, class_id, section_id, attendance_date, status, remarks, marked_by";
            $insertParams = [$studentId, $classId, $sectionId, $date, $status, $remarks, $currentUserId];
            $insertTypes = 'iiisssi';
            
            if ($subjectId) {
                $sql .= ", subject_id";
                $insertParams[] = $subjectId;
                $insertTypes .= 'i';
            }
            
            $sql .= ") VALUES (?, ?, ?, ?, ?, ?, ?";
            if ($subjectId) {
                $sql .= ", ?";
            }
            $sql .= ")";
            
            executeQuery($sql, $insertTypes, $insertParams);
        }
        
        $savedCount++;
    }
    
    // Log activity
    logActivity($currentUserId, 'Mark Attendance', 'Attendance', 
                "Marked attendance for $savedCount students on $date");
    
    commitTransaction();
    jsonResponse(true, "Attendance saved successfully for $savedCount students!");
    
} catch (Exception $e) {
    rollbackTransaction();
    jsonResponse(false, 'Error: ' . $e->getMessage());
}

